"""Lesson data 56-60: Escatología, Romanos 8, Level 2 final"""
M = "el-GR-Chirp3-HD-Charon"
F = "el-GR-Chirp3-HD-Kore"

L56={"num":56,"intro_es":"Μάθημα πεντήκοντα ἕξ. Lección cincuenta y seis. Hoy aprenderás sobre la segunda venida y el fin de los tiempos. Escucha.",
"dialogue":[(M,"Ἔσονται σημεῖα ἐν ἡλίῳ καὶ σελήνῃ καὶ ἄστροις."),(M,"Καὶ τότε ὄψονται τὸν υἱὸν τοῦ ἀνθρώπου ἐρχόμενον ἐν νεφέλῃ.")],
"context_es":"Habrá señales en el sol, la luna y las estrellas. Y entonces verán al Hijo del Hombre viniendo en una nube.",
"vocab":[{"gr":"ἀποκάλυψις","es":"revelación","note_es":"ἀποκάλυψις significa revelación. De aquí viene Apocalipsis. No significa destrucción sino revelación. Aparece dieciocho veces. Escucha."},{"gr":"ἥλιος","es":"sol","note_es":"ἥλιος significa sol. Escucha."},{"gr":"σελήνη","es":"luna","note_es":"σελήνη significa luna. Escucha."},{"gr":"νεφέλη","es":"nube","note_es":"νεφέλη significa nube. Escucha."},{"gr":"ὁ υἱὸς τοῦ ἀνθρώπου","es":"el Hijo del Hombre","note_es":"ὁ υἱὸς τοῦ ἀνθρώπου es el Hijo del Hombre. El título que Jesús más usa para sí mismo. Escucha."},{"gr":"τότε","es":"entonces","note_es":"τότε significa entonces. Aparece ciento sesenta veces. Escucha."}],
"phrases":[{"gr":"ἔσονται σημεῖα","es":"habrá señales","prompt_es":"Di habrá señales."},{"gr":"ὁ υἱὸς τοῦ ἀνθρώπου","es":"el Hijo del Hombre","prompt_es":"Di el Hijo del Hombre."},{"gr":"ἐρχόμενον ἐν νεφέλῃ","es":"viniendo en una nube","prompt_es":"Di viniendo en una nube."},{"gr":"ἡ ἀποκάλυψις τοῦ κυρίου","es":"la revelación del Señor","prompt_es":"Di la revelación del Señor."},{"gr":"ἐν ἡλίῳ καὶ σελήνῃ","es":"en el sol y la luna","prompt_es":"Di en el sol y la luna."},{"gr":"τότε ὄψονται","es":"entonces verán","prompt_es":"Di entonces verán."}],
"recon":[{"prompt_es":"Di habrá señales en el sol y la luna.","answer_gr":"Ἔσονται σημεῖα ἐν ἡλίῳ καὶ σελήνῃ.","answer_voice":M},{"prompt_es":"Di el Hijo del Hombre viniendo en una nube.","answer_gr":"Ὁ υἱὸς τοῦ ἀνθρώπου ἐρχόμενος ἐν νεφέλῃ.","answer_voice":M},{"prompt_es":"Di la revelación del Señor.","answer_gr":"Ἡ ἀποκάλυψις τοῦ κυρίου.","answer_voice":M}],
"verse":{"gr":"Καὶ τότε ὄψονται τὸν υἱὸν τοῦ ἀνθρώπου ἐρχόμενον ἐν νεφέλῃ μετὰ δυνάμεως καὶ δόξης πολλῆς.","voice":M,"ref_es":"Lucas veintiuno veintisiete:","explain_es":"Entonces verán al Hijo del Hombre viniendo en una nube con poder y gran gloria. ὄψονται, verán. δυνάμεως, poder. δόξης, gloria."},
"closing_es":"Aprendiste escatología: ἀποκάλυψις revelación, ἥλιος sol, σελήνη luna, νεφέλη nube, τότε entonces. Εἰρήνη σοι."}

L57={"num":57,"intro_es":"Μάθημα πεντήκοντα ἑπτά. Lección cincuenta y siete. Hoy leerás Romanos ocho veintiocho al treinta y uno. Escucha.",
"dialogue":[(M,"Οἴδαμεν δὲ ὅτι τοῖς ἀγαπῶσιν τὸν θεὸν πάντα συνεργεῖ εἰς ἀγαθόν."),(M,"Εἰ ὁ θεὸς ὑπὲρ ἡμῶν, τίς καθ᾽ ἡμῶν;")],
"context_es":"Sabemos que a los que aman a Dios, todas las cosas cooperan para bien. Si Dios es por nosotros, ¿quién contra nosotros?",
"vocab":[{"gr":"συνεργέω","es":"cooperar, obrar juntos","note_es":"συνεργέω significa cooperar u obrar juntos. Viene de σύν, juntos, y ἔργον, obra. Escucha."},{"gr":"ὑπέρ","es":"por, a favor de","note_es":"ὑπέρ con genitivo significa por o a favor de. ὑπὲρ ἡμῶν, por nosotros. Escucha."},{"gr":"κατά","es":"contra (con genitivo)","note_es":"κατά con genitivo significa contra. καθ᾽ ἡμῶν, contra nosotros. Ya conoces κατά con acusativo que significa según o a lo largo de. Escucha."},{"gr":"προγινώσκω","es":"conocer de antemano","note_es":"προγινώσκω significa conocer de antemano. Viene de πρό, antes, y γινώσκω, conocer. Escucha."},{"gr":"δικαιόω","es":"justificar","note_es":"δικαιόω significa justificar o declarar justo. Viene de δίκαιος, justo. Aparece treinta y nueve veces. Escucha."},{"gr":"δοξάζω","es":"glorificar","note_es":"δοξάζω significa glorificar. Viene de δόξα, gloria. Escucha."}],
"phrases":[{"gr":"πάντα συνεργεῖ εἰς ἀγαθόν","es":"todas las cosas cooperan para bien","prompt_es":"Di todas las cosas cooperan para bien."},{"gr":"εἰ ὁ θεὸς ὑπὲρ ἡμῶν","es":"si Dios es por nosotros","prompt_es":"Di si Dios es por nosotros."},{"gr":"τίς καθ᾽ ἡμῶν;","es":"¿quién contra nosotros?","prompt_es":"Di quién contra nosotros."},{"gr":"οὓς ἐδικαίωσεν, τούτους καὶ ἐδόξασεν","es":"a los que justificó, a estos también glorificó","prompt_es":"Di a los que justificó, también glorificó."},{"gr":"τοῖς ἀγαπῶσιν τὸν θεόν","es":"a los que aman a Dios","prompt_es":"Di a los que aman a Dios. ἀγαπῶσιν es participio dativo plural."},{"gr":"ὑπὲρ ἡμῶν","es":"por nosotros","prompt_es":"Di por nosotros."}],
"recon":[{"prompt_es":"Di sabemos que a los que aman a Dios todas las cosas cooperan para bien.","answer_gr":"Οἴδαμεν ὅτι τοῖς ἀγαπῶσιν τὸν θεὸν πάντα συνεργεῖ εἰς ἀγαθόν.","answer_voice":M},{"prompt_es":"Di si Dios es por nosotros, quién contra nosotros.","answer_gr":"Εἰ ὁ θεὸς ὑπὲρ ἡμῶν, τίς καθ᾽ ἡμῶν;","answer_voice":M}],
"verse":{"gr":"Εἰ ὁ θεὸς ὑπὲρ ἡμῶν, τίς καθ᾽ ἡμῶν;","voice":M,"ref_es":"Romanos ocho treinta y uno:","explain_es":"Si Dios es por nosotros, ¿quién contra nosotros? Reconoces cada palabra. εἰ, si. θεός, Dios. ὑπέρ, por. ἡμῶν, nosotros. τίς, quién. κατά, contra."},
"closing_es":"Leíste Romanos ocho. Aprendiste: συνεργέω cooperar, ὑπέρ por, κατά contra, δικαιόω justificar, δοξάζω glorificar. Εἰρήνη σοι."}

L58={"num":58,"intro_es":"Μάθημα πεντήκοντα ὀκτώ. Lección cincuenta y ocho. Hoy leerás el final de Romanos ocho: nada nos separará del amor de Dios. Escucha.",
"dialogue":[(M,"Τίς ἡμᾶς χωρίσει ἀπὸ τῆς ἀγάπης τοῦ Χριστοῦ;"),(M,"Ἐν τούτοις πᾶσιν ὑπερνικῶμεν διὰ τοῦ ἀγαπήσαντος ἡμᾶς.")],
"context_es":"¿Quién nos separará del amor de Cristo? En todas estas cosas somos más que vencedores por medio del que nos amó.",
"vocab":[{"gr":"χωρίζω","es":"separar","note_es":"χωρίζω significa separar. τίς ἡμᾶς χωρίσει, quién nos separará. Escucha."},{"gr":"ὑπερνικάω","es":"ser más que vencedor","note_es":"ὑπερνικάω significa ser más que vencedor. Viene de ὑπέρ, sobre, y νικάω, vencer. Escucha."},{"gr":"νικάω","es":"vencer","note_es":"νικάω significa vencer. De aquí viene el nombre Nike. Escucha."},{"gr":"θάνατος","es":"muerte","note_es":"Ya conoces θάνατος, muerte. Ni la muerte nos separará. Escucha."},{"gr":"ἄγγελος","es":"ángel, mensajero","note_es":"ἄγγελος significa ángel o mensajero. Aparece ciento setenta y cinco veces. Escucha."},{"gr":"κτίσις","es":"creación","note_es":"κτίσις significa creación. Ninguna otra criatura nos separará. Escucha."}],
"phrases":[{"gr":"τίς ἡμᾶς χωρίσει;","es":"¿quién nos separará?","prompt_es":"Di quién nos separará."},{"gr":"ἀπὸ τῆς ἀγάπης τοῦ Χριστοῦ","es":"del amor de Cristo","prompt_es":"Di del amor de Cristo."},{"gr":"ὑπερνικῶμεν","es":"somos más que vencedores","prompt_es":"Di somos más que vencedores."},{"gr":"διὰ τοῦ ἀγαπήσαντος ἡμᾶς","es":"por medio del que nos amó","prompt_es":"Di por medio del que nos amó. ἀγαπήσαντος es participio aoristo: el que amó."},{"gr":"οὔτε θάνατος οὔτε ζωή","es":"ni muerte ni vida","prompt_es":"Di ni muerte ni vida. οὔτε significa ni."},{"gr":"οὔτε ἄγγελοι","es":"ni ángeles","prompt_es":"Di ni ángeles."}],
"recon":[{"prompt_es":"Di quién nos separará del amor de Cristo.","answer_gr":"Τίς ἡμᾶς χωρίσει ἀπὸ τῆς ἀγάπης τοῦ Χριστοῦ;","answer_voice":M},{"prompt_es":"Di somos más que vencedores por medio del que nos amó.","answer_gr":"Ὑπερνικῶμεν διὰ τοῦ ἀγαπήσαντος ἡμᾶς.","answer_voice":M},{"prompt_es":"Di ni muerte ni vida ni ángeles.","answer_gr":"Οὔτε θάνατος οὔτε ζωὴ οὔτε ἄγγελοι.","answer_voice":M}],
"verse":{"gr":"Πέπεισμαι γὰρ ὅτι οὔτε θάνατος οὔτε ζωὴ οὔτε ἄγγελοι... δυνήσεται ἡμᾶς χωρίσαι ἀπὸ τῆς ἀγάπης τοῦ θεοῦ τῆς ἐν Χριστῷ Ἰησοῦ τῷ κυρίῳ ἡμῶν.","voice":M,"ref_es":"Romanos ocho treinta y ocho al treinta y nueve:","explain_es":"Estoy convencido de que ni la muerte ni la vida ni los ángeles podrán separarnos del amor de Dios que es en Cristo Jesús nuestro Señor. πέπεισμαι, estoy convencido. δυνήσεται, podrá. χωρίσαι, separar."},
"closing_es":"Leíste el final de Romanos ocho. Aprendiste: χωρίζω separar, νικάω vencer, ὑπερνικάω ser más que vencedor, ἄγγελος ángel, κτίσις creación. Εἰρήνη σοι."}

L59={"num":59,"intro_es":"Μάθημα πεντήκοντα ἐννέα. Lección cincuenta y nueve. Hoy aprenderás vocabulario de la Pasión de Cristo. Escucha.",
"dialogue":[(M,"Ἐσταύρωσαν αὐτόν."),(F,"Πάτερ, ἄφες αὐτοῖς· οὐ γὰρ οἴδασιν τί ποιοῦσιν."),(M,"Τετέλεσται.")],
"context_es":"Lo crucificaron. Padre, perdónalos, porque no saben lo que hacen. Consumado es.",
"vocab":[{"gr":"σταυρός","es":"cruz","note_es":"σταυρός significa cruz. Aparece veintisiete veces. Escucha."},{"gr":"σταυρόω","es":"crucificar","note_es":"σταυρόω significa crucificar. ἐσταύρωσαν es crucificaron. Aparece cuarenta y seis veces. Escucha."},{"gr":"αἷμα","es":"sangre","note_es":"αἷμα significa sangre. Aparece noventa y siete veces. τὸ αἷμα, la sangre. Escucha."},{"gr":"τετέλεσται","es":"consumado es, está terminado","note_es":"τετέλεσται significa está terminado o consumado es. Es el perfecto pasivo de τελέω, completar. Las últimas palabras de Jesús en Juan. Escucha."},{"gr":"μνημεῖον","es":"sepulcro, tumba","note_es":"μνημεῖον significa sepulcro o tumba. Aparece cuarenta veces. Escucha."},{"gr":"ἐγείρω","es":"levantar, resucitar","note_es":"Ya conoces ἐγείρω. ἠγέρθη, fue levantado, resucitó. Escucha."}],
"phrases":[{"gr":"ἐσταύρωσαν αὐτόν","es":"lo crucificaron","prompt_es":"Di lo crucificaron."},{"gr":"Πάτερ, ἄφες αὐτοῖς","es":"Padre, perdónalos","prompt_es":"Di Padre, perdónalos."},{"gr":"τετέλεσται","es":"consumado es","prompt_es":"Di consumado es. Las últimas palabras de Jesús en la cruz."},{"gr":"τὸ αἷμα τοῦ Χριστοῦ","es":"la sangre de Cristo","prompt_es":"Di la sangre de Cristo."},{"gr":"ὁ σταυρὸς τοῦ Χριστοῦ","es":"la cruz de Cristo","prompt_es":"Di la cruz de Cristo."},{"gr":"ἠγέρθη τῇ τρίτῃ ἡμέρᾳ","es":"resucitó al tercer día","prompt_es":"Di resucitó al tercer día."}],
"recon":[{"prompt_es":"Narra: lo crucificaron.","answer_gr":"Ἐσταύρωσαν αὐτόν.","answer_voice":M},{"prompt_es":"Di las palabras de Jesús: Padre, perdónalos, porque no saben lo que hacen.","answer_gr":"Πάτερ, ἄφες αὐτοῖς· οὐ γὰρ οἴδασιν τί ποιοῦσιν.","answer_voice":M},{"prompt_es":"Di consumado es.","answer_gr":"Τετέλεσται.","answer_voice":M},{"prompt_es":"Di resucitó al tercer día.","answer_gr":"Ἠγέρθη τῇ τρίτῃ ἡμέρᾳ.","answer_voice":M}],
"verse":{"gr":"Τετέλεσται.","voice":M,"ref_es":"Juan diecinueve treinta, las últimas palabras de Jesús:","explain_es":"Consumado es. Una sola palabra en griego. τετέλεσται, perfecto pasivo de τελέω. Significa que la obra está completa, terminada, cumplida."},
"closing_es":"Aprendiste la Pasión: σταυρός cruz, σταυρόω crucificar, αἷμα sangre, τετέλεσται consumado es, μνημεῖον sepulcro. Εἰρήνη σοι."}

L60={"num":60,"intro_es":"Μάθημα ἑξήκοντα. Lección sesenta. Última lección del segundo nivel. Hoy leerás el prólogo del evangelio de Juan. Escucha.",
"dialogue":[(M,"Ἐν ἀρχῇ ἦν ὁ λόγος, καὶ ὁ λόγος ἦν πρὸς τὸν θεόν, καὶ θεὸς ἦν ὁ λόγος."),(M,"Οὗτος ἦν ἐν ἀρχῇ πρὸς τὸν θεόν."),(M,"Πάντα δι᾽ αὐτοῦ ἐγένετο."),(M,"Καὶ ὁ λόγος σὰρξ ἐγένετο καὶ ἐσκήνωσεν ἐν ἡμῖν.")],
"context_es":"En el principio era el Verbo, y el Verbo era con Dios, y el Verbo era Dios. Este era en el principio con Dios. Todas las cosas fueron hechas por él. Y el Verbo se hizo carne y habitó entre nosotros.",
"vocab":[{"gr":"ἀρχή","es":"principio, comienzo","note_es":"ἀρχή significa principio o comienzo. Aparece cincuenta y cinco veces. ἐν ἀρχῇ, en el principio. Escucha."},{"gr":"σάρξ","es":"carne","note_es":"σάρξ significa carne. Aparece ciento cuarenta y siete veces. ἡ σάρξ, la carne. Escucha."},{"gr":"σκηνόω","es":"habitar en tienda, morar","note_es":"σκηνόω significa habitar en tienda o morar. Viene de σκηνή, tienda. ἐσκήνωσεν ἐν ἡμῖν, habitó entre nosotros. Escucha."},{"gr":"μονογενής","es":"unigénito","note_es":"Ya conoces μονογενής, unigénito. Viene de μόνος, solo, y γένος, nacimiento. Escucha."},{"gr":"πλήρης","es":"lleno","note_es":"Ya conoces πλήρης, lleno. πλήρης χάριτος καὶ ἀληθείας, lleno de gracia y verdad. Escucha."},{"gr":"χάρις","es":"gracia","note_es":"Ya conoces χάρις, gracia. χάριν ἀντὶ χάριτος, gracia sobre gracia. Escucha."}],
"phrases":[{"gr":"ἐν ἀρχῇ ἦν ὁ λόγος","es":"en el principio era el Verbo","prompt_es":"Di en el principio era el Verbo."},{"gr":"ὁ λόγος ἦν πρὸς τὸν θεόν","es":"el Verbo era con Dios","prompt_es":"Di el Verbo era con Dios."},{"gr":"θεὸς ἦν ὁ λόγος","es":"el Verbo era Dios","prompt_es":"Di el Verbo era Dios."},{"gr":"πάντα δι᾽ αὐτοῦ ἐγένετο","es":"todas las cosas fueron hechas por él","prompt_es":"Di todas las cosas fueron hechas por él."},{"gr":"ὁ λόγος σὰρξ ἐγένετο","es":"el Verbo se hizo carne","prompt_es":"Di el Verbo se hizo carne."},{"gr":"ἐσκήνωσεν ἐν ἡμῖν","es":"habitó entre nosotros","prompt_es":"Di habitó entre nosotros."},{"gr":"πλήρης χάριτος καὶ ἀληθείας","es":"lleno de gracia y verdad","prompt_es":"Di lleno de gracia y verdad."}],
"recon":[{"prompt_es":"Recita Juan uno uno: en el principio era el Verbo.","answer_gr":"Ἐν ἀρχῇ ἦν ὁ λόγος.","answer_voice":M},{"prompt_es":"Continúa: y el Verbo era con Dios.","answer_gr":"Καὶ ὁ λόγος ἦν πρὸς τὸν θεόν.","answer_voice":M},{"prompt_es":"Continúa: y el Verbo era Dios.","answer_gr":"Καὶ θεὸς ἦν ὁ λόγος.","answer_voice":M},{"prompt_es":"Di el Verbo se hizo carne y habitó entre nosotros.","answer_gr":"Ὁ λόγος σὰρξ ἐγένετο καὶ ἐσκήνωσεν ἐν ἡμῖν.","answer_voice":M}],
"verse":{"gr":"Ἐν ἀρχῇ ἦν ὁ λόγος, καὶ ὁ λόγος ἦν πρὸς τὸν θεόν, καὶ θεὸς ἦν ὁ λόγος.","voice":M,"ref_es":"Juan uno uno:","explain_es":"En el principio era el Verbo, y el Verbo era con Dios, y el Verbo era Dios. Reconoces cada palabra. ἀρχῇ, principio. ἦν, era. λόγος, Verbo. πρός, con. θεόν, Dios."},
"closing_es":"Felicidades. Has completado el segundo nivel, sesenta lecciones. Puedes leer y entender el prólogo de Juan. Conoces más de cuatrocientas palabras que cubren más del ochenta y cinco por ciento del Nuevo Testamento. En el tercer nivel leerás textos completos y aprenderás vocabulario avanzado. Εἰρήνη σοι."}
