"""Lesson data 81-85: Extended reading — John prologue, Romans 8, Psalm 23 LXX"""
M = "el-GR-Chirp3-HD-Charon"
F = "el-GR-Chirp3-HD-Kore"

L81={"num":81,"intro_es":"Μάθημα ὀγδοήκοντα ἕν. Lección ochenta y uno. Hoy leerás Juan uno uno al cinco verso por verso. Escucha.",
"dialogue":[(M,"Ἐν ἀρχῇ ἦν ὁ λόγος, καὶ ὁ λόγος ἦν πρὸς τὸν θεόν, καὶ θεὸς ἦν ὁ λόγος."),(M,"Οὗτος ἦν ἐν ἀρχῇ πρὸς τὸν θεόν."),(M,"Πάντα δι᾽ αὐτοῦ ἐγένετο, καὶ χωρὶς αὐτοῦ ἐγένετο οὐδὲ ἕν."),(M,"Ἐν αὐτῷ ζωὴ ἦν, καὶ ἡ ζωὴ ἦν τὸ φῶς τῶν ἀνθρώπων."),(M,"Καὶ τὸ φῶς ἐν τῇ σκοτίᾳ φαίνει, καὶ ἡ σκοτία αὐτὸ οὐ κατέλαβεν.")],
"context_es":"En el principio era el Verbo. El Verbo era con Dios. El Verbo era Dios. Todo fue hecho por él. En él estaba la vida, y la vida era la luz de los hombres. La luz brilla en la oscuridad, y la oscuridad no la venció.",
"vocab":[{"gr":"φαίνω","es":"brillar, aparecer","note_es":"φαίνω significa brillar o aparecer. τὸ φῶς φαίνει, la luz brilla. Escucha."},{"gr":"καταλαμβάνω","es":"alcanzar, vencer, comprender","note_es":"καταλαμβάνω significa alcanzar, vencer o comprender. κατέλαβεν puede significar venció o comprendió. Doble sentido en Juan. Escucha."},{"gr":"οὐδέ","es":"ni, ni siquiera","note_es":"οὐδέ significa ni o ni siquiera. οὐδὲ ἕν, ni una sola cosa. Escucha."},{"gr":"χωρίς","es":"sin, aparte de","note_es":"Ya conoces χωρίς. χωρὶς αὐτοῦ, sin él. Escucha."},{"gr":"δι᾽ αὐτοῦ","es":"por medio de él","note_es":"δι᾽ αὐτοῦ es la contracción de διά αὐτοῦ. Por medio de él. Escucha."},{"gr":"ἐν αὐτῷ","es":"en él","note_es":"ἐν αὐτῷ, en él. ἐν αὐτῷ ζωὴ ἦν, en él estaba la vida. Escucha."}],
"phrases":[{"gr":"ἐν ἀρχῇ ἦν ὁ λόγος","es":"en el principio era el Verbo","prompt_es":"Di en el principio era el Verbo."},{"gr":"ὁ λόγος ἦν πρὸς τὸν θεόν","es":"el Verbo era con Dios","prompt_es":"Di el Verbo era con Dios."},{"gr":"θεὸς ἦν ὁ λόγος","es":"el Verbo era Dios","prompt_es":"Di el Verbo era Dios. Nota el orden: Dios era el Verbo."},{"gr":"πάντα δι᾽ αὐτοῦ ἐγένετο","es":"todo fue hecho por él","prompt_es":"Di todo fue hecho por él."},{"gr":"ἐν αὐτῷ ζωὴ ἦν","es":"en él estaba la vida","prompt_es":"Di en él estaba la vida."},{"gr":"τὸ φῶς ἐν τῇ σκοτίᾳ φαίνει","es":"la luz brilla en la oscuridad","prompt_es":"Di la luz brilla en la oscuridad."}],
"recon":[{"prompt_es":"Recita Juan uno uno completo.","answer_gr":"Ἐν ἀρχῇ ἦν ὁ λόγος, καὶ ὁ λόγος ἦν πρὸς τὸν θεόν, καὶ θεὸς ἦν ὁ λόγος.","answer_voice":M},{"prompt_es":"Di todo fue hecho por él y sin él nada fue hecho.","answer_gr":"Πάντα δι᾽ αὐτοῦ ἐγένετο, καὶ χωρὶς αὐτοῦ ἐγένετο οὐδὲ ἕν.","answer_voice":M},{"prompt_es":"Di la luz brilla en la oscuridad.","answer_gr":"Τὸ φῶς ἐν τῇ σκοτίᾳ φαίνει.","answer_voice":M}],
"verse":{"gr":"Καὶ τὸ φῶς ἐν τῇ σκοτίᾳ φαίνει, καὶ ἡ σκοτία αὐτὸ οὐ κατέλαβεν.","voice":M,"ref_es":"Juan uno cinco:","explain_es":"Y la luz brilla en la oscuridad, y la oscuridad no la venció. φαίνει, brilla. σκοτία, oscuridad. κατέλαβεν, venció o comprendió."},
"closing_es":"Leíste Juan uno uno al cinco. Cada palabra te es familiar. Εἰρήνη σοι."}

L82={"num":82,"intro_es":"Μάθημα ὀγδοήκοντα δύο. Lección ochenta y dos. Hoy leerás Juan uno seis al catorce: el Verbo se hizo carne. Escucha.",
"dialogue":[(M,"Ἐγένετο ἄνθρωπος ἀπεσταλμένος παρὰ θεοῦ, ὄνομα αὐτῷ Ἰωάννης."),(M,"Τὸ φῶς τὸ ἀληθινόν, ὃ φωτίζει πάντα ἄνθρωπον."),(M,"Καὶ ὁ λόγος σὰρξ ἐγένετο καὶ ἐσκήνωσεν ἐν ἡμῖν, καὶ ἐθεασάμεθα τὴν δόξαν αὐτοῦ.")],
"context_es":"Hubo un hombre enviado de Dios, su nombre era Juan. La luz verdadera que alumbra a todo hombre. Y el Verbo se hizo carne y habitó entre nosotros, y vimos su gloria.",
"vocab":[{"gr":"ἀπεσταλμένος","es":"enviado (participio perfecto)","note_es":"ἀπεσταλμένος es el participio perfecto de ἀποστέλλω. Enviado. Escucha."},{"gr":"φωτίζω","es":"iluminar, alumbrar","note_es":"φωτίζω significa iluminar. Viene de φῶς, luz. Escucha."},{"gr":"θεάομαι","es":"contemplar, ver","note_es":"θεάομαι significa contemplar o ver con atención. ἐθεασάμεθα, contemplamos. De aquí viene teatro. Escucha."},{"gr":"σκηνόω","es":"habitar en tienda","note_es":"Ya conoces σκηνόω. ἐσκήνωσεν ἐν ἡμῖν, habitó entre nosotros. Literalmente, puso su tienda entre nosotros. Escucha."},{"gr":"πλήρης","es":"lleno","note_es":"Ya conoces πλήρης. πλήρης χάριτος καὶ ἀληθείας, lleno de gracia y verdad. Escucha."},{"gr":"χάριν ἀντὶ χάριτος","es":"gracia sobre gracia","note_es":"χάριν ἀντὶ χάριτος significa gracia sobre gracia. ἀντί aquí significa sobre o en lugar de. Escucha."}],
"phrases":[{"gr":"ἐγένετο ἄνθρωπος ἀπεσταλμένος παρὰ θεοῦ","es":"hubo un hombre enviado de Dios","prompt_es":"Di hubo un hombre enviado de Dios."},{"gr":"τὸ φῶς τὸ ἀληθινόν","es":"la luz verdadera","prompt_es":"Di la luz verdadera."},{"gr":"ὁ λόγος σὰρξ ἐγένετο","es":"el Verbo se hizo carne","prompt_es":"Di el Verbo se hizo carne."},{"gr":"ἐσκήνωσεν ἐν ἡμῖν","es":"habitó entre nosotros","prompt_es":"Di habitó entre nosotros."},{"gr":"ἐθεασάμεθα τὴν δόξαν αὐτοῦ","es":"contemplamos su gloria","prompt_es":"Di contemplamos su gloria."},{"gr":"πλήρης χάριτος καὶ ἀληθείας","es":"lleno de gracia y verdad","prompt_es":"Di lleno de gracia y verdad."}],
"recon":[{"prompt_es":"Di el Verbo se hizo carne y habitó entre nosotros.","answer_gr":"Ὁ λόγος σὰρξ ἐγένετο καὶ ἐσκήνωσεν ἐν ἡμῖν.","answer_voice":M},{"prompt_es":"Di contemplamos su gloria, lleno de gracia y verdad.","answer_gr":"Ἐθεασάμεθα τὴν δόξαν αὐτοῦ, πλήρης χάριτος καὶ ἀληθείας.","answer_voice":M},{"prompt_es":"Di gracia sobre gracia.","answer_gr":"Χάριν ἀντὶ χάριτος.","answer_voice":M}],
"verse":{"gr":"Καὶ ὁ λόγος σὰρξ ἐγένετο καὶ ἐσκήνωσεν ἐν ἡμῖν, καὶ ἐθεασάμεθα τὴν δόξαν αὐτοῦ, δόξαν ὡς μονογενοῦς παρὰ πατρός, πλήρης χάριτος καὶ ἀληθείας.","voice":M,"ref_es":"Juan uno catorce:","explain_es":"Y el Verbo se hizo carne y habitó entre nosotros, y contemplamos su gloria, gloria como del unigénito del Padre, lleno de gracia y verdad."},
"closing_es":"Leíste Juan uno seis al catorce. El Verbo se hizo carne. Εἰρήνη σοι."}

L83={"num":83,"intro_es":"Μάθημα ὀγδοήκοντα τρία. Lección ochenta y tres. Hoy leerás Romanos ocho treinta y uno al treinta y nueve completo. Escucha.",
"dialogue":[(M,"Εἰ ὁ θεὸς ὑπὲρ ἡμῶν, τίς καθ᾽ ἡμῶν;"),(M,"Τίς ἡμᾶς χωρίσει ἀπὸ τῆς ἀγάπης τοῦ Χριστοῦ;"),(M,"Ἐν τούτοις πᾶσιν ὑπερνικῶμεν διὰ τοῦ ἀγαπήσαντος ἡμᾶς.")],
"context_es":"Si Dios es por nosotros, quién contra nosotros. Quién nos separará del amor de Cristo. En todas estas cosas somos más que vencedores.",
"vocab":[{"gr":"ὑπερνικάω","es":"más que vencer","note_es":"Ya conoces ὑπερνικάω. ὑπερνικῶμεν, somos más que vencedores. Escucha."},{"gr":"χωρίζω","es":"separar","note_es":"Ya conoces χωρίζω. χωρίσει, separará. Escucha."},{"gr":"θλῖψις","es":"tribulación","note_es":"Ya conoces θλῖψις. Ni tribulación ni angustia nos separará. Escucha."},{"gr":"στενοχωρία","es":"angustia","note_es":"στενοχωρία significa angustia. Viene de στενός, estrecho, y χῶρος, espacio. Espacio estrecho, angustia. Escucha."},{"gr":"διωγμός","es":"persecución","note_es":"διωγμός significa persecución. Viene de διώκω, perseguir. Escucha."},{"gr":"πείθω","es":"convencer, persuadir","note_es":"πείθω significa convencer. πέπεισμαι es estoy convencido, perfecto pasivo. Escucha."}],
"phrases":[{"gr":"εἰ ὁ θεὸς ὑπὲρ ἡμῶν, τίς καθ᾽ ἡμῶν;","es":"si Dios por nosotros, quién contra nosotros","prompt_es":"Di si Dios es por nosotros, quién contra nosotros."},{"gr":"τίς ἡμᾶς χωρίσει ἀπὸ τῆς ἀγάπης τοῦ Χριστοῦ;","es":"quién nos separará del amor de Cristo","prompt_es":"Di quién nos separará del amor de Cristo."},{"gr":"ὑπερνικῶμεν διὰ τοῦ ἀγαπήσαντος ἡμᾶς","es":"somos más que vencedores por el que nos amó","prompt_es":"Di somos más que vencedores por el que nos amó."},{"gr":"πέπεισμαι γάρ","es":"porque estoy convencido","prompt_es":"Di porque estoy convencido."},{"gr":"οὔτε θάνατος οὔτε ζωή","es":"ni muerte ni vida","prompt_es":"Di ni muerte ni vida."},{"gr":"οὔτε ὕψωμα οὔτε βάθος","es":"ni lo alto ni lo profundo","prompt_es":"Di ni lo alto ni lo profundo."}],
"recon":[{"prompt_es":"Recita Romanos ocho treinta y uno.","answer_gr":"Εἰ ὁ θεὸς ὑπὲρ ἡμῶν, τίς καθ᾽ ἡμῶν;","answer_voice":M},{"prompt_es":"Di quién nos separará del amor de Cristo.","answer_gr":"Τίς ἡμᾶς χωρίσει ἀπὸ τῆς ἀγάπης τοῦ Χριστοῦ;","answer_voice":M},{"prompt_es":"Di estoy convencido de que ni muerte ni vida podrán separarnos.","answer_gr":"Πέπεισμαι ὅτι οὔτε θάνατος οὔτε ζωὴ δυνήσεται ἡμᾶς χωρίσαι ἀπὸ τῆς ἀγάπης τοῦ θεοῦ.","answer_voice":M}],
"verse":{"gr":"Πέπεισμαι γὰρ ὅτι οὔτε θάνατος οὔτε ζωὴ οὔτε ἄγγελοι οὔτε ἀρχαὶ οὔτε ἐνεστῶτα οὔτε μέλλοντα οὔτε δυνάμεις οὔτε ὕψωμα οὔτε βάθος οὔτε τις κτίσις ἑτέρα δυνήσεται ἡμᾶς χωρίσαι ἀπὸ τῆς ἀγάπης τοῦ θεοῦ τῆς ἐν Χριστῷ Ἰησοῦ τῷ κυρίῳ ἡμῶν.","voice":M,"ref_es":"Romanos ocho treinta y ocho al treinta y nueve:","explain_es":"Estoy convencido de que ni la muerte, ni la vida, ni ángeles, ni principados, ni lo presente, ni lo por venir, ni poderes, ni lo alto, ni lo profundo, ni ninguna otra criatura podrá separarnos del amor de Dios que es en Cristo Jesús nuestro Señor."},
"closing_es":"Leíste Romanos ocho completo. Nada nos separará del amor de Dios. Εἰρήνη σοι."}

L84={"num":84,"intro_es":"Μάθημα ὀγδοήκοντα τέσσαρα. Lección ochenta y cuatro. Hoy leerás el Salmo veintitrés en la Septuaginta. Escucha.",
"dialogue":[(M,"Κύριος ποιμαίνει με καὶ οὐδέν με ὑστερήσει."),(M,"Εἰς τόπον χλόης, ἐκεῖ με κατεσκήνωσεν· ἐπὶ ὕδατος ἀναπαύσεως ἐξέθρεψέν με.")],
"context_es":"El Señor es mi pastor, nada me faltará. En lugar de verdes pastos me hizo descansar. Junto a aguas de reposo me crió.",
"vocab":[{"gr":"ποιμαίνω","es":"pastorear","note_es":"ποιμαίνω significa pastorear. Viene de ποιμήν, pastor. Κύριος ποιμαίνει με, el Señor me pastorea. Escucha."},{"gr":"ὑστερέω","es":"faltar, carecer","note_es":"ὑστερέω significa faltar o carecer. οὐδέν με ὑστερήσει, nada me faltará. Escucha."},{"gr":"χλόη","es":"hierba verde, pasto","note_es":"χλόη significa hierba verde o pasto. εἰς τόπον χλόης, en lugar de pastos verdes. Escucha."},{"gr":"ἀνάπαυσις","es":"descanso, reposo","note_es":"Ya conoces ἀνάπαυσις. ὕδατος ἀναπαύσεως, aguas de reposo. Escucha."},{"gr":"ῥάβδος","es":"vara, bastón","note_es":"ῥάβδος significa vara o bastón. ἡ ῥάβδος σου, tu vara. Escucha."},{"gr":"τράπεζα","es":"mesa","note_es":"τράπεζα significa mesa. ἡτοίμασας ἐνώπιόν μου τράπεζαν, preparaste mesa delante de mí. Escucha."}],
"phrases":[{"gr":"Κύριος ποιμαίνει με","es":"el Señor me pastorea","prompt_es":"Di el Señor me pastorea."},{"gr":"οὐδέν με ὑστερήσει","es":"nada me faltará","prompt_es":"Di nada me faltará."},{"gr":"εἰς τόπον χλόης","es":"en lugar de pastos verdes","prompt_es":"Di en lugar de pastos verdes."},{"gr":"ἐπὶ ὕδατος ἀναπαύσεως","es":"junto a aguas de reposo","prompt_es":"Di junto a aguas de reposo."},{"gr":"ἡ ῥάβδος σου καὶ ἡ βακτηρία σου","es":"tu vara y tu cayado","prompt_es":"Di tu vara y tu cayado."},{"gr":"τὸ ἔλεός σου καταδιώξεταί με","es":"tu misericordia me seguirá","prompt_es":"Di tu misericordia me seguirá."}],
"recon":[{"prompt_es":"Recita el Salmo veintitrés: el Señor me pastorea, nada me faltará.","answer_gr":"Κύριος ποιμαίνει με καὶ οὐδέν με ὑστερήσει.","answer_voice":M},{"prompt_es":"Di en lugar de pastos verdes me hizo descansar.","answer_gr":"Εἰς τόπον χλόης ἐκεῖ με κατεσκήνωσεν.","answer_voice":M},{"prompt_es":"Di tu misericordia me seguirá todos los días de mi vida.","answer_gr":"Τὸ ἔλεός σου καταδιώξεταί με πάσας τὰς ἡμέρας τῆς ζωῆς μου.","answer_voice":M}],
"verse":{"gr":"Κύριος ποιμαίνει με καὶ οὐδέν με ὑστερήσει.","voice":M,"ref_es":"Salmo veintitrés uno en la Septuaginta:","explain_es":"El Señor me pastorea y nada me faltará. ποιμαίνει, pastorea. οὐδέν, nada. ὑστερήσει, faltará. Tu primera lectura de la Septuaginta."},
"closing_es":"Leíste el Salmo veintitrés en griego. Tu primera lectura de la Septuaginta. ποιμαίνω pastorear, ὑστερέω faltar, χλόη pasto, ἀνάπαυσις reposo. Εἰρήνη σοι."}

L85={"num":85,"intro_es":"Μάθημα ὀγδοήκοντα πέντε. Lección ochenta y cinco. Hoy leerás primera de Corintios quince: la resurrección. Escucha.",
"dialogue":[(M,"Εἰ δὲ Χριστὸς κηρύσσεται ὅτι ἐκ νεκρῶν ἐγήγερται, πῶς λέγουσίν τινες ἐν ὑμῖν ὅτι ἀνάστασις νεκρῶν οὐκ ἔστιν;"),(M,"Νυνὶ δὲ Χριστὸς ἐγήγερται ἐκ νεκρῶν, ἀπαρχὴ τῶν κεκοιμημένων.")],
"context_es":"Si se predica que Cristo resucitó de los muertos, ¿cómo dicen algunos que no hay resurrección? Pero ahora Cristo ha resucitado, primicias de los que durmieron.",
"vocab":[{"gr":"ἀπαρχή","es":"primicias","note_es":"ἀπαρχή significa primicias, el primer fruto. Viene de ἀπό y ἀρχή. Cristo es las primicias de la resurrección. Escucha."},{"gr":"κοιμάομαι","es":"dormir (eufemismo para morir)","note_es":"κοιμάομαι significa dormir. En el NT es eufemismo para morir. οἱ κεκοιμημένοι, los que durmieron, los muertos. Escucha."},{"gr":"φθαρτός","es":"corruptible","note_es":"φθαρτός significa corruptible. Lo opuesto de ἄφθαρτος. Escucha."},{"gr":"ἀφθαρσία","es":"incorrupción","note_es":"ἀφθαρσία significa incorrupción. Escucha."},{"gr":"νίκη","es":"victoria","note_es":"νίκη significa victoria. ποῦ σου, θάνατε, τὸ νῖκος; ¿Dónde está, oh muerte, tu victoria? Escucha."},{"gr":"κέντρον","es":"aguijón","note_es":"κέντρον significa aguijón. ποῦ σου, θάνατε, τὸ κέντρον; ¿Dónde está tu aguijón? Escucha."}],
"phrases":[{"gr":"Χριστὸς ἐγήγερται ἐκ νεκρῶν","es":"Cristo ha resucitado de los muertos","prompt_es":"Di Cristo ha resucitado de los muertos."},{"gr":"ἀπαρχὴ τῶν κεκοιμημένων","es":"primicias de los que durmieron","prompt_es":"Di primicias de los que durmieron."},{"gr":"σπείρεται ἐν φθορᾷ, ἐγείρεται ἐν ἀφθαρσίᾳ","es":"se siembra en corrupción, resucita en incorrupción","prompt_es":"Di se siembra en corrupción, resucita en incorrupción."},{"gr":"ποῦ σου, θάνατε, τὸ νῖκος;","es":"¿dónde, oh muerte, tu victoria?","prompt_es":"Di dónde, oh muerte, tu victoria."},{"gr":"ποῦ σου, θάνατε, τὸ κέντρον;","es":"¿dónde, oh muerte, tu aguijón?","prompt_es":"Di dónde, oh muerte, tu aguijón."},{"gr":"τῷ θεῷ χάρις","es":"gracias a Dios","prompt_es":"Di gracias a Dios."}],
"recon":[{"prompt_es":"Di Cristo ha resucitado, primicias de los que durmieron.","answer_gr":"Χριστὸς ἐγήγερται ἐκ νεκρῶν, ἀπαρχὴ τῶν κεκοιμημένων.","answer_voice":M},{"prompt_es":"Di dónde, oh muerte, tu victoria.","answer_gr":"Ποῦ σου, θάνατε, τὸ νῖκος;","answer_voice":M},{"prompt_es":"Di gracias a Dios que nos da la victoria.","answer_gr":"Τῷ δὲ θεῷ χάρις τῷ διδόντι ἡμῖν τὸ νῖκος.","answer_voice":M}],
"verse":{"gr":"Ποῦ σου, θάνατε, τὸ νῖκος; ποῦ σου, θάνατε, τὸ κέντρον;","voice":M,"ref_es":"Primera de Corintios quince cincuenta y cinco:","explain_es":"¿Dónde está, oh muerte, tu victoria? ¿Dónde está, oh muerte, tu aguijón? ποῦ, dónde. θάνατε, muerte en vocativo. νῖκος, victoria. κέντρον, aguijón."},
"closing_es":"Leíste primera de Corintios quince: ἀπαρχή primicias, κοιμάομαι dormir, νίκη victoria, κέντρον aguijón. Εἰρήνη σοι."}
