"""Lesson data 76-80: Colossians, 2 Timothy, Titus, reading practice"""
M = "el-GR-Chirp3-HD-Charon"
F = "el-GR-Chirp3-HD-Kore"

L76={"num":76,"intro_es":"Μάθημα ἑβδομήκοντα ἕξ. Lección setenta y seis. Hoy leerás Colosenses: Cristo preeminente. Escucha.",
"dialogue":[(M,"Αὐτός ἐστιν εἰκὼν τοῦ θεοῦ τοῦ ἀοράτου, πρωτότοκος πάσης κτίσεως."),(M,"Ὅτι ἐν αὐτῷ ἐκτίσθη τὰ πάντα.")],
"context_es":"Él es la imagen del Dios invisible, el primogénito de toda creación. Porque en él fueron creadas todas las cosas.",
"vocab":[{"gr":"εἰκών","es":"imagen","note_es":"εἰκών significa imagen. Aparece veintitrés veces. De aquí viene ícono. Escucha."},{"gr":"ἀόρατος","es":"invisible","note_es":"ἀόρατος significa invisible. Viene de ἀ, sin, y ὁράω, ver. Lo que no se puede ver. Escucha."},{"gr":"πρωτότοκος","es":"primogénito","note_es":"πρωτότοκος significa primogénito. Viene de πρῶτος, primero, y τίκτω, dar a luz. Escucha."},{"gr":"κτίζω","es":"crear","note_es":"κτίζω significa crear. ἐκτίσθη es fue creado, aoristo pasivo. Escucha."},{"gr":"πρό","es":"antes de","note_es":"Ya conoces πρό, antes. πρὸ πάντων, antes de todas las cosas. Escucha."},{"gr":"συνίστημι","es":"mantener unido","note_es":"συνίστημι significa mantener unido o sostener. Viene de σύν y ἵστημι. τὰ πάντα ἐν αὐτῷ συνέστηκεν, todas las cosas en él subsisten. Escucha."}],
"phrases":[{"gr":"εἰκὼν τοῦ θεοῦ τοῦ ἀοράτου","es":"imagen del Dios invisible","prompt_es":"Di imagen del Dios invisible."},{"gr":"πρωτότοκος πάσης κτίσεως","es":"primogénito de toda creación","prompt_es":"Di primogénito de toda creación."},{"gr":"ἐν αὐτῷ ἐκτίσθη τὰ πάντα","es":"en él fueron creadas todas las cosas","prompt_es":"Di en él fueron creadas todas las cosas."},{"gr":"τὰ πάντα δι᾽ αὐτοῦ καὶ εἰς αὐτὸν ἔκτισται","es":"todo fue creado por él y para él","prompt_es":"Di todo fue creado por él y para él."},{"gr":"αὐτός ἐστιν πρὸ πάντων","es":"él es antes de todas las cosas","prompt_es":"Di él es antes de todas las cosas."},{"gr":"τὰ πάντα ἐν αὐτῷ συνέστηκεν","es":"todas las cosas en él subsisten","prompt_es":"Di todas las cosas en él subsisten."}],
"recon":[{"prompt_es":"Di él es la imagen del Dios invisible.","answer_gr":"Αὐτός ἐστιν εἰκὼν τοῦ θεοῦ τοῦ ἀοράτου.","answer_voice":M},{"prompt_es":"Di en él fueron creadas todas las cosas.","answer_gr":"Ἐν αὐτῷ ἐκτίσθη τὰ πάντα.","answer_voice":M},{"prompt_es":"Di todas las cosas en él subsisten.","answer_gr":"Τὰ πάντα ἐν αὐτῷ συνέστηκεν.","answer_voice":M}],
"verse":{"gr":"Αὐτός ἐστιν εἰκὼν τοῦ θεοῦ τοῦ ἀοράτου, πρωτότοκος πάσης κτίσεως.","voice":M,"ref_es":"Colosenses uno quince:","explain_es":"Él es la imagen del Dios invisible, el primogénito de toda creación. εἰκών, imagen. ἀοράτου, invisible. πρωτότοκος, primogénito. κτίσεως, creación."},
"closing_es":"Aprendiste Colosenses: εἰκών imagen, ἀόρατος invisible, πρωτότοκος primogénito, κτίζω crear. Εἰρήνη σοι."}

L77={"num":77,"intro_es":"Μάθημα ἑβδομήκοντα ἑπτά. Lección setenta y siete. Hoy leerás segunda de Timoteo: la Escritura inspirada. Escucha.",
"dialogue":[(M,"Πᾶσα γραφὴ θεόπνευστος καὶ ὠφέλιμος πρὸς διδασκαλίαν, πρὸς ἐλεγμόν, πρὸς ἐπανόρθωσιν, πρὸς παιδείαν τὴν ἐν δικαιοσύνῃ.")],
"context_es":"Toda Escritura es inspirada por Dios y útil para enseñar, para redargüir, para corregir, para instruir en justicia.",
"vocab":[{"gr":"θεόπνευστος","es":"inspirada por Dios","note_es":"θεόπνευστος significa inspirada por Dios. Viene de θεός, Dios, y πνέω, soplar. Soplada por Dios. Solo aparece aquí. Escucha."},{"gr":"ὠφέλιμος","es":"útil, provechoso","note_es":"ὠφέλιμος significa útil o provechoso. Escucha."},{"gr":"διδασκαλία","es":"enseñanza, doctrina","note_es":"διδασκαλία significa enseñanza o doctrina. Viene de διδάσκω. Escucha."},{"gr":"παιδεία","es":"instrucción, disciplina","note_es":"παιδεία significa instrucción o disciplina. En koiné NO significa tormento como en griego moderno. Viene de παῖς, niño. La formación del niño. Escucha."},{"gr":"ἐπανόρθωσις","es":"corrección","note_es":"ἐπανόρθωσις significa corrección. Viene de ἐπί, sobre, ἀνά, arriba, y ὀρθός, recto. Enderezar de nuevo. Escucha."},{"gr":"ἄρτιος","es":"completo, equipado","note_es":"ἄρτιος significa completo o equipado. ἵνα ἄρτιος ᾖ ὁ τοῦ θεοῦ ἄνθρωπος, para que el hombre de Dios sea completo. Escucha."}],
"phrases":[{"gr":"πᾶσα γραφὴ θεόπνευστος","es":"toda Escritura es inspirada por Dios","prompt_es":"Di toda Escritura es inspirada por Dios."},{"gr":"ὠφέλιμος πρὸς διδασκαλίαν","es":"útil para enseñar","prompt_es":"Di útil para enseñar."},{"gr":"πρὸς παιδείαν τὴν ἐν δικαιοσύνῃ","es":"para instruir en justicia","prompt_es":"Di para instruir en justicia."},{"gr":"ὁ τοῦ θεοῦ ἄνθρωπος","es":"el hombre de Dios","prompt_es":"Di el hombre de Dios."},{"gr":"πρὸς πᾶν ἔργον ἀγαθὸν ἐξηρτισμένος","es":"equipado para toda buena obra","prompt_es":"Di equipado para toda buena obra."},{"gr":"τὸν καλὸν ἀγῶνα ἠγώνισμαι","es":"he peleado la buena batalla","prompt_es":"Di he peleado la buena batalla."}],
"recon":[{"prompt_es":"Di toda Escritura es inspirada por Dios y útil para enseñar.","answer_gr":"Πᾶσα γραφὴ θεόπνευστος καὶ ὠφέλιμος πρὸς διδασκαλίαν.","answer_voice":M},{"prompt_es":"Di he peleado la buena batalla.","answer_gr":"Τὸν καλὸν ἀγῶνα ἠγώνισμαι.","answer_voice":M},{"prompt_es":"Di el hombre de Dios.","answer_gr":"Ὁ τοῦ θεοῦ ἄνθρωπος.","answer_voice":M}],
"verse":{"gr":"Πᾶσα γραφὴ θεόπνευστος καὶ ὠφέλιμος.","voice":M,"ref_es":"Segunda de Timoteo tres dieciséis:","explain_es":"Toda Escritura es inspirada por Dios y útil. γραφή, Escritura. θεόπνευστος, inspirada por Dios. ὠφέλιμος, útil."},
"closing_es":"Aprendiste segunda de Timoteo: θεόπνευστος inspirada, ὠφέλιμος útil, διδασκαλία enseñanza, παιδεία instrucción. Εἰρήνη σοι."}

L78={"num":78,"intro_es":"Μάθημα ἑβδομήκοντα ὀκτώ. Lección setenta y ocho. Hoy practicarás lectura continua: el Magníficat de María. Lucas uno. Escucha.",
"dialogue":[(F,"Μεγαλύνει ἡ ψυχή μου τὸν κύριον, καὶ ἠγαλλίασεν τὸ πνεῦμά μου ἐπὶ τῷ θεῷ τῷ σωτῆρί μου.")],
"context_es":"Mi alma engrandece al Señor, y mi espíritu se regocijó en Dios mi Salvador.",
"vocab":[{"gr":"μεγαλύνω","es":"engrandecer, magnificar","note_es":"μεγαλύνω significa engrandecer o magnificar. Viene de μέγας, grande. Escucha."},{"gr":"ἀγαλλιάω","es":"regocijarse","note_es":"ἀγαλλιάω significa regocijarse con gran gozo. Escucha."},{"gr":"σωτήρ","es":"salvador","note_es":"σωτήρ significa salvador. Aparece veinticuatro veces. Es una de las pocas palabras con sufijo τήρ que sobrevive en el NT. Escucha."},{"gr":"ταπεινός","es":"humilde","note_es":"ταπεινός significa humilde o de baja condición. Escucha."},{"gr":"δυνατός","es":"poderoso","note_es":"δυνατός significa poderoso. ὁ δυνατός, el Poderoso. Escucha."},{"gr":"ἔλεος","es":"misericordia","note_es":"Ya conoces ἔλεος. τὸ ἔλεος αὐτοῦ, su misericordia. Escucha."}],
"phrases":[{"gr":"μεγαλύνει ἡ ψυχή μου τὸν κύριον","es":"mi alma engrandece al Señor","prompt_es":"Di mi alma engrandece al Señor."},{"gr":"ἠγαλλίασεν τὸ πνεῦμά μου","es":"mi espíritu se regocijó","prompt_es":"Di mi espíritu se regocijó."},{"gr":"ἐπὶ τῷ θεῷ τῷ σωτῆρί μου","es":"en Dios mi Salvador","prompt_es":"Di en Dios mi Salvador."},{"gr":"ἐπέβλεψεν ἐπὶ τὴν ταπείνωσιν τῆς δούλης αὐτοῦ","es":"miró la humildad de su sierva","prompt_es":"Di miró la humildad de su sierva."},{"gr":"ἐποίησέν μοι μεγάλα ὁ δυνατός","es":"el Poderoso ha hecho grandes cosas por mí","prompt_es":"Di el Poderoso ha hecho grandes cosas por mí."},{"gr":"τὸ ἔλεος αὐτοῦ εἰς γενεὰς καὶ γενεάς","es":"su misericordia de generación en generación","prompt_es":"Di su misericordia de generación en generación."}],
"recon":[{"prompt_es":"Recita el Magníficat: mi alma engrandece al Señor.","answer_gr":"Μεγαλύνει ἡ ψυχή μου τὸν κύριον.","answer_voice":F},{"prompt_es":"Continúa: mi espíritu se regocijó en Dios mi Salvador.","answer_gr":"Ἠγαλλίασεν τὸ πνεῦμά μου ἐπὶ τῷ θεῷ τῷ σωτῆρί μου.","answer_voice":F},{"prompt_es":"Di el Poderoso ha hecho grandes cosas por mí.","answer_gr":"Ἐποίησέν μοι μεγάλα ὁ δυνατός.","answer_voice":F}],
"verse":{"gr":"Μεγαλύνει ἡ ψυχή μου τὸν κύριον, καὶ ἠγαλλίασεν τὸ πνεῦμά μου ἐπὶ τῷ θεῷ τῷ σωτῆρί μου.","voice":F,"ref_es":"Lucas uno cuarenta y seis al cuarenta y siete:","explain_es":"Mi alma engrandece al Señor, y mi espíritu se regocijó en Dios mi Salvador. μεγαλύνει, engrandece. ψυχή, alma. ἠγαλλίασεν, se regocijó. σωτῆρι, Salvador."},
"closing_es":"Leíste el Magníficat: μεγαλύνω engrandecer, ἀγαλλιάω regocijarse, σωτήρ salvador, ταπεινός humilde. Εἰρήνη σοι."}

L79={"num":79,"intro_es":"Μάθημα ἑβδομήκοντα ἐννέα. Lección setenta y nueve. Hoy leerás el Benedictus de Zacarías. Lucas uno. Escucha.",
"dialogue":[(M,"Εὐλογητὸς κύριος ὁ θεὸς τοῦ Ἰσραήλ, ὅτι ἐπεσκέψατο καὶ ἐποίησεν λύτρωσιν τῷ λαῷ αὐτοῦ.")],
"context_es":"Bendito el Señor Dios de Israel, porque ha visitado y redimido a su pueblo.",
"vocab":[{"gr":"ἐπισκέπτομαι","es":"visitar, cuidar","note_es":"ἐπισκέπτομαι significa visitar o cuidar. Viene de ἐπί, sobre, y σκέπτομαι, mirar. Mirar sobre alguien con cuidado. Escucha."},{"gr":"λύτρωσις","es":"redención","note_es":"λύτρωσις significa redención. Viene de λύτρον, rescate, que viene de λύω, soltar. Escucha."},{"gr":"σωτηρία","es":"salvación","note_es":"σωτηρία significa salvación. Viene de σῴζω, salvar. Aparece cuarenta y cinco veces. Escucha."},{"gr":"ἐπαγγελία","es":"promesa","note_es":"Ya conoces ἐπαγγελία, promesa. Zacarías habla de las promesas a Abraham. Escucha."},{"gr":"ὅρκος","es":"juramento","note_es":"ὅρκος significa juramento. Escucha."},{"gr":"λατρεύω","es":"servir, adorar","note_es":"Ya conoces λατρεύω. λατρεύειν αὐτῷ, servirle. Escucha."}],
"phrases":[{"gr":"εὐλογητὸς κύριος ὁ θεὸς τοῦ Ἰσραήλ","es":"bendito el Señor Dios de Israel","prompt_es":"Di bendito el Señor Dios de Israel."},{"gr":"ἐπεσκέψατο καὶ ἐποίησεν λύτρωσιν","es":"visitó e hizo redención","prompt_es":"Di visitó e hizo redención."},{"gr":"τῷ λαῷ αὐτοῦ","es":"a su pueblo","prompt_es":"Di a su pueblo."},{"gr":"σωτηρίαν ἐξ ἐχθρῶν ἡμῶν","es":"salvación de nuestros enemigos","prompt_es":"Di salvación de nuestros enemigos."},{"gr":"ἐν ὁσιότητι καὶ δικαιοσύνῃ","es":"en santidad y justicia","prompt_es":"Di en santidad y justicia."},{"gr":"λατρεύειν αὐτῷ ἀφόβως","es":"servirle sin temor","prompt_es":"Di servirle sin temor. ἀφόβως significa sin temor."}],
"recon":[{"prompt_es":"Di bendito el Señor Dios de Israel.","answer_gr":"Εὐλογητὸς κύριος ὁ θεὸς τοῦ Ἰσραήλ.","answer_voice":M},{"prompt_es":"Di visitó e hizo redención a su pueblo.","answer_gr":"Ἐπεσκέψατο καὶ ἐποίησεν λύτρωσιν τῷ λαῷ αὐτοῦ.","answer_voice":M},{"prompt_es":"Di servirle sin temor.","answer_gr":"Λατρεύειν αὐτῷ ἀφόβως.","answer_voice":M}],
"verse":{"gr":"Εὐλογητὸς κύριος ὁ θεὸς τοῦ Ἰσραήλ, ὅτι ἐπεσκέψατο καὶ ἐποίησεν λύτρωσιν τῷ λαῷ αὐτοῦ.","voice":M,"ref_es":"Lucas uno sesenta y ocho:","explain_es":"Bendito el Señor Dios de Israel, porque visitó e hizo redención a su pueblo. ἐπεσκέψατο, visitó. λύτρωσιν, redención. λαῷ, pueblo."},
"closing_es":"Leíste el Benedictus: ἐπισκέπτομαι visitar, λύτρωσις redención, σωτηρία salvación. Εἰρήνη σοι."}

L80={"num":80,"intro_es":"Μάθημα ὀγδοήκοντα. Lección ochenta. Hoy leerás el Nunc Dimittis de Simeón. Lucas dos. Escucha.",
"dialogue":[(M,"Νῦν ἀπολύεις τὸν δοῦλόν σου, δέσποτα, κατὰ τὸ ῥῆμά σου ἐν εἰρήνῃ· ὅτι εἶδον οἱ ὀφθαλμοί μου τὸ σωτήριόν σου.")],
"context_es":"Ahora despides a tu siervo, Señor, conforme a tu palabra en paz. Porque han visto mis ojos tu salvación.",
"vocab":[{"gr":"ἀπολύω","es":"despedir, liberar","note_es":"Ya conoces ἀπολύω. Aquí significa despedir en paz, dejar ir. Escucha."},{"gr":"δεσπότης","es":"señor, amo","note_es":"δεσπότης significa señor o amo. Es más fuerte que κύριος. Implica autoridad absoluta. Escucha."},{"gr":"ῥῆμα","es":"palabra, dicho","note_es":"ῥῆμα significa palabra o dicho. En koiné es una palabra hablada, un pronunciamiento. NO es verbo como en griego moderno. Aparece sesenta y ocho veces. Escucha."},{"gr":"σωτήριον","es":"salvación","note_es":"σωτήριον significa salvación. Es la forma neutra de σωτήριος. Escucha."},{"gr":"ἑτοιμάζω","es":"preparar","note_es":"ἑτοιμάζω significa preparar. ὃ ἡτοίμασας, lo que preparaste. Escucha."},{"gr":"ἀποκάλυψις","es":"revelación","note_es":"Ya conoces ἀποκάλυψις. φῶς εἰς ἀποκάλυψιν ἐθνῶν, luz para revelación de las naciones. Escucha."}],
"phrases":[{"gr":"νῦν ἀπολύεις τὸν δοῦλόν σου","es":"ahora despides a tu siervo","prompt_es":"Di ahora despides a tu siervo."},{"gr":"κατὰ τὸ ῥῆμά σου ἐν εἰρήνῃ","es":"conforme a tu palabra en paz","prompt_es":"Di conforme a tu palabra en paz."},{"gr":"εἶδον οἱ ὀφθαλμοί μου τὸ σωτήριόν σου","es":"mis ojos han visto tu salvación","prompt_es":"Di mis ojos han visto tu salvación."},{"gr":"φῶς εἰς ἀποκάλυψιν ἐθνῶν","es":"luz para revelación de las naciones","prompt_es":"Di luz para revelación de las naciones."},{"gr":"δόξαν λαοῦ σου Ἰσραήλ","es":"gloria de tu pueblo Israel","prompt_es":"Di gloria de tu pueblo Israel."},{"gr":"ὃ ἡτοίμασας κατὰ πρόσωπον πάντων τῶν λαῶν","es":"lo que preparaste ante todos los pueblos","prompt_es":"Di lo que preparaste ante todos los pueblos."}],
"recon":[{"prompt_es":"Recita el Nunc Dimittis: ahora despides a tu siervo, Señor.","answer_gr":"Νῦν ἀπολύεις τὸν δοῦλόν σου, δέσποτα.","answer_voice":M},{"prompt_es":"Continúa: conforme a tu palabra en paz.","answer_gr":"Κατὰ τὸ ῥῆμά σου ἐν εἰρήνῃ.","answer_voice":M},{"prompt_es":"Di mis ojos han visto tu salvación.","answer_gr":"Εἶδον οἱ ὀφθαλμοί μου τὸ σωτήριόν σου.","answer_voice":M}],
"verse":{"gr":"Νῦν ἀπολύεις τὸν δοῦλόν σου, δέσποτα, κατὰ τὸ ῥῆμά σου ἐν εἰρήνῃ.","voice":M,"ref_es":"Lucas dos veintinueve:","explain_es":"Ahora despides a tu siervo, Señor, conforme a tu palabra en paz. ἀπολύεις, despides. δοῦλον, siervo. δέσποτα, Señor. ῥῆμα, palabra. εἰρήνῃ, paz."},
"closing_es":"Leíste el Nunc Dimittis: δεσπότης señor, ῥῆμα palabra, σωτήριον salvación, ἑτοιμάζω preparar. Has completado ochenta lecciones. Εἰρήνη σοι."}
