"""Lesson data 86-90: Final lessons — review, evaluation, 1 Cor 13"""
M = "el-GR-Chirp3-HD-Charon"
F = "el-GR-Chirp3-HD-Kore"

L86={"num":86,"intro_es":"Μάθημα ὀγδοήκοντα ἕξ. Lección ochenta y seis. Hoy leerás Efesios dos: salvados por gracia. Escucha.",
"dialogue":[(M,"Τῇ γὰρ χάριτί ἐστε σεσῳσμένοι διὰ πίστεως· καὶ τοῦτο οὐκ ἐξ ὑμῶν, θεοῦ τὸ δῶρον· οὐκ ἐξ ἔργων, ἵνα μή τις καυχήσηται.")],
"context_es":"Porque por gracia son salvos por medio de la fe, y esto no de ustedes, es don de Dios. No por obras, para que nadie se gloríe.",
"vocab":[{"gr":"σεσῳσμένοι","es":"salvados (participio perfecto)","note_es":"σεσῳσμένοι es el participio perfecto pasivo de σῴζω. Salvados, estado presente de haber sido salvados. Escucha."},{"gr":"δῶρον","es":"don, regalo","note_es":"δῶρον significa don o regalo. θεοῦ τὸ δῶρον, don de Dios. Escucha."},{"gr":"καυχάομαι","es":"gloriarse, jactarse","note_es":"καυχάομαι significa gloriarse o jactarse. ἵνα μή τις καυχήσηται, para que nadie se gloríe. Escucha."},{"gr":"ποίημα","es":"obra, creación","note_es":"ποίημα significa obra o creación. Viene de ποιέω, hacer. αὐτοῦ γάρ ἐσμεν ποίημα, somos su obra. De aquí viene poema. Escucha."},{"gr":"κτίζω","es":"crear","note_es":"Ya conoces κτίζω. κτισθέντες ἐν Χριστῷ, creados en Cristo. Escucha."},{"gr":"προετοιμάζω","es":"preparar de antemano","note_es":"προετοιμάζω significa preparar de antemano. Viene de πρό, antes, y ἑτοιμάζω, preparar. Escucha."}],
"phrases":[{"gr":"τῇ χάριτί ἐστε σεσῳσμένοι","es":"por gracia son salvos","prompt_es":"Di por gracia son salvos."},{"gr":"διὰ πίστεως","es":"por medio de la fe","prompt_es":"Di por medio de la fe."},{"gr":"θεοῦ τὸ δῶρον","es":"don de Dios","prompt_es":"Di don de Dios."},{"gr":"οὐκ ἐξ ἔργων","es":"no por obras","prompt_es":"Di no por obras."},{"gr":"αὐτοῦ ἐσμεν ποίημα","es":"somos su obra","prompt_es":"Di somos su obra."},{"gr":"κτισθέντες ἐν Χριστῷ Ἰησοῦ","es":"creados en Cristo Jesús","prompt_es":"Di creados en Cristo Jesús."}],
"recon":[{"prompt_es":"Recita Efesios dos ocho: por gracia son salvos por medio de la fe.","answer_gr":"Τῇ γὰρ χάριτί ἐστε σεσῳσμένοι διὰ πίστεως.","answer_voice":M},{"prompt_es":"Di esto no de ustedes, es don de Dios.","answer_gr":"Τοῦτο οὐκ ἐξ ὑμῶν, θεοῦ τὸ δῶρον.","answer_voice":M},{"prompt_es":"Di no por obras, para que nadie se gloríe.","answer_gr":"Οὐκ ἐξ ἔργων, ἵνα μή τις καυχήσηται.","answer_voice":M}],
"verse":{"gr":"Τῇ γὰρ χάριτί ἐστε σεσῳσμένοι διὰ πίστεως· καὶ τοῦτο οὐκ ἐξ ὑμῶν, θεοῦ τὸ δῶρον.","voice":M,"ref_es":"Efesios dos ocho:","explain_es":"Por gracia son salvos por medio de la fe, y esto no de ustedes, es don de Dios. χάριτι, por gracia. σεσῳσμένοι, salvados. πίστεως, fe. δῶρον, don."},
"closing_es":"Leíste Efesios dos: σεσῳσμένοι salvados, δῶρον don, καυχάομαι gloriarse, ποίημα obra. Εἰρήνη σοι."}

L87={"num":87,"intro_es":"Μάθημα ὀγδοήκοντα ἑπτά. Lección ochenta y siete. Hoy repasarás con un diálogo libre combinando todo lo aprendido. Escucha.",
"dialogue":[(F,"Χαῖρε! Πόθεν εἶ;"),(M,"ἀπὸ Γαλιλαίας. Μαθητής εἰμι τοῦ Ἰησοῦ."),(F,"Τί διδάσκει;"),(M,"Διδάσκει ὅτι ὁ θεὸς ἀγάπη ἐστίν, καὶ ὅτι δεῖ ἡμᾶς ἀγαπᾶν ἀλλήλους."),(F,"Πιστεύεις ὅτι ἠγέρθη ἐκ νεκρῶν;"),(M,"ναί, πιστεύω. Ἐγώ εἰμι μάρτυς. Εἶδον αὐτὸν τοῖς ὀφθαλμοῖς μου.")],
"context_es":"Un diálogo completo usando vocabulario de los tres niveles. Saludos, origen, enseñanza, fe, testimonio.",
"vocab":[{"gr":"ἀλλήλους","es":"unos a otros","note_es":"Ya conoces ἀλλήλους. ἀγαπᾶν ἀλλήλους, amarse unos a otros. Escucha."},{"gr":"μάρτυς","es":"testigo","note_es":"Ya conoces μάρτυς. ἐγώ εἰμι μάρτυς, yo soy testigo. Escucha."},{"gr":"τοῖς ὀφθαλμοῖς μου","es":"con mis ojos","note_es":"τοῖς ὀφθαλμοῖς μου, con mis propios ojos. Dativo instrumental. Escucha."},{"gr":"κηρύσσω","es":"predicar","note_es":"Ya conoces κηρύσσω. κηρύσσομεν Χριστὸν ἐσταυρωμένον, predicamos a Cristo crucificado. Escucha."},{"gr":"ἐσταυρωμένος","es":"crucificado","note_es":"ἐσταυρωμένος es el participio perfecto de σταυρόω. Crucificado, estado permanente. Escucha."},{"gr":"ἀναστάς","es":"habiendo resucitado","note_es":"ἀναστάς es el participio aoristo de ἀνίστημι. Habiendo resucitado. Escucha."}],
"phrases":[{"gr":"μαθητής εἰμι τοῦ Ἰησοῦ","es":"soy discípulo de Jesús","prompt_es":"Di soy discípulo de Jesús."},{"gr":"ὁ θεὸς ἀγάπη ἐστίν","es":"Dios es amor","prompt_es":"Di Dios es amor."},{"gr":"δεῖ ἡμᾶς ἀγαπᾶν ἀλλήλους","es":"debemos amarnos unos a otros","prompt_es":"Di debemos amarnos unos a otros."},{"gr":"εἶδον αὐτὸν τοῖς ὀφθαλμοῖς μου","es":"lo vi con mis propios ojos","prompt_es":"Di lo vi con mis propios ojos."},{"gr":"κηρύσσομεν Χριστὸν ἐσταυρωμένον","es":"predicamos a Cristo crucificado","prompt_es":"Di predicamos a Cristo crucificado."},{"gr":"Χριστὸς ἀναστὰς ἐκ νεκρῶν","es":"Cristo habiendo resucitado de los muertos","prompt_es":"Di Cristo habiendo resucitado de los muertos."}],
"recon":[{"other_gr":"Χαῖρε! Πόθεν εἶ;","other_voice":F,"prompt_es":"Saluda y di de dónde eres.","answer_gr":"Εἰρήνη σοι. ἀπὸ Γαλιλαίας εἰμί.","answer_voice":M},{"other_gr":"Τί διδάσκει ὁ Ἰησοῦς;","other_voice":F,"prompt_es":"Di que enseña que Dios es amor.","answer_gr":"Διδάσκει ὅτι ὁ θεὸς ἀγάπη ἐστίν.","answer_voice":M},{"other_gr":"Πιστεύεις ὅτι ἠγέρθη;","other_voice":F,"prompt_es":"Di que sí, lo viste con tus ojos.","answer_gr":"ναί, πιστεύω. Εἶδον αὐτὸν τοῖς ὀφθαλμοῖς μου.","answer_voice":M},{"prompt_es":"Di predicamos a Cristo crucificado y resucitado.","answer_gr":"Κηρύσσομεν Χριστὸν ἐσταυρωμένον καὶ ἀναστάντα.","answer_voice":M}],
"verse":{"gr":"Ἡμεῖς κηρύσσομεν Χριστὸν ἐσταυρωμένον.","voice":M,"ref_es":"Primera de Corintios uno veintitrés:","explain_es":"Nosotros predicamos a Cristo crucificado. ἡμεῖς, nosotros. κηρύσσομεν, predicamos. ἐσταυρωμένον, crucificado."},
"closing_es":"Tuviste un diálogo completo en griego koiné usando vocabulario de los tres niveles. Εἰρήνη σοι."}

L88={"num":88,"intro_es":"Μάθημα ὀγδοήκοντα ὀκτώ. Lección ochenta y ocho. Hoy narrarás la parábola del hijo pródigo. Lucas quince. Escucha.",
"dialogue":[(M,"Ἄνθρωπός τις εἶχεν δύο υἱούς."),(M,"Καὶ εἶπεν ὁ νεώτερος αὐτῶν τῷ πατρί· Πάτερ, δός μοι τὸ ἐπιβάλλον μέρος τῆς οὐσίας."),(M,"Καὶ ἀναστὰς ἦλθεν πρὸς τὸν πατέρα ἑαυτοῦ."),(M,"Ὁ δὲ πατὴρ εἶπεν τοῖς δούλοις αὐτοῦ· Ταχὺ ἐξενέγκατε στολὴν τὴν πρώτην.")],
"context_es":"Un hombre tenía dos hijos. El menor dijo: Padre, dame mi parte. Y levantándose vino a su padre. El padre dijo a sus siervos: pronto, traigan la mejor ropa.",
"vocab":[{"gr":"νεώτερος","es":"más joven, menor","note_es":"νεώτερος significa más joven. Comparativo de νέος. Escucha."},{"gr":"οὐσία","es":"hacienda, propiedad","note_es":"οὐσία significa hacienda o propiedad. En koiné es bienes materiales. Escucha."},{"gr":"μέρος","es":"parte, porción","note_es":"μέρος significa parte o porción. Escucha."},{"gr":"μακράν","es":"lejos","note_es":"μακράν significa lejos. ἀπεδήμησεν εἰς χώραν μακράν, viajó a un país lejano. Escucha."},{"gr":"λιμός","es":"hambre, hambruna","note_es":"λιμός significa hambre o hambruna. Escucha."},{"gr":"στολή","es":"vestidura, ropa","note_es":"στολή significa vestidura. τὴν στολὴν τὴν πρώτην, la mejor vestidura. Escucha."}],
"phrases":[{"gr":"ἄνθρωπός τις εἶχεν δύο υἱούς","es":"un hombre tenía dos hijos","prompt_es":"Di un hombre tenía dos hijos."},{"gr":"Πάτερ, δός μοι","es":"Padre, dame","prompt_es":"Di Padre, dame."},{"gr":"ἀναστὰς ἦλθεν πρὸς τὸν πατέρα","es":"levantándose vino a su padre","prompt_es":"Di levantándose vino a su padre."},{"gr":"Πάτερ, ἥμαρτον εἰς τὸν οὐρανόν","es":"Padre, he pecado contra el cielo","prompt_es":"Di Padre, he pecado contra el cielo."},{"gr":"οὐκέτι εἰμὶ ἄξιος κληθῆναι υἱός σου","es":"ya no soy digno de ser llamado tu hijo","prompt_es":"Di ya no soy digno de ser llamado tu hijo."},{"gr":"νεκρὸς ἦν καὶ ἀνέζησεν","es":"estaba muerto y ha revivido","prompt_es":"Di estaba muerto y ha revivido."}],
"recon":[{"prompt_es":"Comienza la parábola: un hombre tenía dos hijos.","answer_gr":"Ἄνθρωπός τις εἶχεν δύο υἱούς.","answer_voice":M},{"prompt_es":"Di Padre, he pecado contra el cielo y delante de ti.","answer_gr":"Πάτερ, ἥμαρτον εἰς τὸν οὐρανὸν καὶ ἐνώπιόν σου.","answer_voice":M},{"prompt_es":"Di estaba muerto y ha revivido, estaba perdido y fue hallado.","answer_gr":"Νεκρὸς ἦν καὶ ἀνέζησεν, ἀπολωλὼς καὶ εὑρέθη.","answer_voice":M}],
"verse":{"gr":"Οὗτος ὁ υἱός μου νεκρὸς ἦν καὶ ἀνέζησεν, ἦν ἀπολωλὼς καὶ εὑρέθη.","voice":M,"ref_es":"Lucas quince veinticuatro:","explain_es":"Este mi hijo estaba muerto y ha revivido, estaba perdido y fue hallado. νεκρός, muerto. ἀνέζησεν, revivió. ἀπολωλώς, perdido. εὑρέθη, fue hallado."},
"closing_es":"Narraste la parábola del hijo pródigo completa. Εἰρήνη σοι."}

L89={"num":89,"intro_es":"Μάθημα ὀγδοήκοντα ἐννέα. Lección ochenta y nueve. Penúltima lección. Hoy leerás primera de Corintios trece completo: el himno al amor. Escucha.",
"dialogue":[(M,"Ἐὰν ταῖς γλώσσαις τῶν ἀνθρώπων λαλῶ καὶ τῶν ἀγγέλων, ἀγάπην δὲ μὴ ἔχω, γέγονα χαλκὸς ἠχῶν."),(M,"Ἡ ἀγάπη μακροθυμεῖ, χρηστεύεται ἡ ἀγάπη."),(M,"Ἡ ἀγάπη οὐδέποτε πίπτει."),(M,"Νυνὶ δὲ μένει πίστις, ἐλπίς, ἀγάπη, τὰ τρία ταῦτα· μείζων δὲ τούτων ἡ ἀγάπη.")],
"context_es":"Si hablo en lenguas de hombres y de ángeles pero no tengo amor, soy bronce que resuena. El amor es paciente, es bondadoso. El amor nunca cae. Permanecen fe, esperanza, amor. El mayor es el amor.",
"vocab":[{"gr":"χαλκός","es":"bronce","note_es":"χαλκός significa bronce. χαλκὸς ἠχῶν, bronce que resuena. Escucha."},{"gr":"κύμβαλον","es":"címbalo","note_es":"κύμβαλον significa címbalo. κύμβαλον ἀλαλάζον, címbalo que retiñe. Escucha."},{"gr":"οὐδέποτε","es":"nunca","note_es":"οὐδέποτε significa nunca. ἡ ἀγάπη οὐδέποτε πίπτει, el amor nunca cae. Escucha."},{"gr":"πίπτω","es":"caer","note_es":"πίπτω significa caer. Escucha."},{"gr":"βλέπομεν","es":"vemos","note_es":"Ya conoces βλέπω. βλέπομεν δι᾽ ἐσόπτρου, vemos por espejo. Escucha."},{"gr":"ἐσόπτρον","es":"espejo","note_es":"ἐσόπτρον significa espejo. δι᾽ ἐσόπτρου ἐν αἰνίγματι, por espejo en enigma. Escucha."}],
"phrases":[{"gr":"ἐὰν ἀγάπην μὴ ἔχω","es":"si no tengo amor","prompt_es":"Di si no tengo amor."},{"gr":"ἡ ἀγάπη μακροθυμεῖ","es":"el amor es paciente","prompt_es":"Di el amor es paciente."},{"gr":"ἡ ἀγάπη οὐδέποτε πίπτει","es":"el amor nunca cae","prompt_es":"Di el amor nunca cae."},{"gr":"βλέπομεν δι᾽ ἐσόπτρου ἐν αἰνίγματι","es":"vemos por espejo en enigma","prompt_es":"Di vemos por espejo en enigma."},{"gr":"τότε δὲ πρόσωπον πρὸς πρόσωπον","es":"entonces cara a cara","prompt_es":"Di entonces cara a cara."},{"gr":"μείζων δὲ τούτων ἡ ἀγάπη","es":"el mayor de ellos es el amor","prompt_es":"Di el mayor de ellos es el amor."}],
"recon":[{"prompt_es":"Di si hablo en lenguas pero no tengo amor, soy bronce que resuena.","answer_gr":"Ἐὰν ταῖς γλώσσαις τῶν ἀνθρώπων λαλῶ, ἀγάπην δὲ μὴ ἔχω, γέγονα χαλκὸς ἠχῶν.","answer_voice":M},{"prompt_es":"Di el amor es paciente, es bondadoso.","answer_gr":"Ἡ ἀγάπη μακροθυμεῖ, χρηστεύεται ἡ ἀγάπη.","answer_voice":M},{"prompt_es":"Di permanecen fe, esperanza, amor. El mayor es el amor.","answer_gr":"Μένει πίστις, ἐλπίς, ἀγάπη. Μείζων δὲ τούτων ἡ ἀγάπη.","answer_voice":M}],
"verse":{"gr":"Νυνὶ δὲ μένει πίστις, ἐλπίς, ἀγάπη, τὰ τρία ταῦτα· μείζων δὲ τούτων ἡ ἀγάπη.","voice":M,"ref_es":"Primera de Corintios trece trece:","explain_es":"Ahora permanecen la fe, la esperanza y el amor, estos tres. Pero el mayor de ellos es el amor. Reconoces cada palabra."},
"closing_es":"Leíste primera de Corintios trece completo. El himno al amor. Εἰρήνη σοι."}

L90={"num":90,"intro_es":"Μάθημα ἐνενήκοντα. Lección noventa. La última lección. Hoy celebramos todo lo que has aprendido. Escucha el prólogo de Juan una última vez.",
"dialogue":[(M,"Ἐν ἀρχῇ ἦν ὁ λόγος, καὶ ὁ λόγος ἦν πρὸς τὸν θεόν, καὶ θεὸς ἦν ὁ λόγος."),(M,"Καὶ ὁ λόγος σὰρξ ἐγένετο καὶ ἐσκήνωσεν ἐν ἡμῖν, πλήρης χάριτος καὶ ἀληθείας."),(M,"Οὕτως γὰρ ἠγάπησεν ὁ θεὸς τὸν κόσμον, ὥστε τὸν υἱὸν τὸν μονογενῆ ἔδωκεν."),(M,"Νυνὶ δὲ μένει πίστις, ἐλπίς, ἀγάπη· μείζων δὲ τούτων ἡ ἀγάπη.")],
"context_es":"En el principio era el Verbo. El Verbo se hizo carne. De tal manera amó Dios al mundo. Permanecen fe, esperanza, amor. Cuatro versículos que resumen todo el Nuevo Testamento. Y ahora los entiendes en griego.",
"vocab":[{"gr":"τελέω","es":"completar, terminar","note_es":"τελέω significa completar o terminar. τετέλεσται, está terminado. Has completado el curso. Escucha."},{"gr":"εὐχαριστία","es":"acción de gracias","note_es":"εὐχαριστία significa acción de gracias. Viene de εὐχαριστέω. Escucha."},{"gr":"δοξάζω","es":"glorificar","note_es":"Ya conoces δοξάζω. δοξάζομεν τὸν θεόν, glorificamos a Dios. Escucha."},{"gr":"ἀμήν","es":"amén, así sea","note_es":"ἀμήν. Así sea. La última palabra. Escucha."}],
"phrases":[{"gr":"ἐν ἀρχῇ ἦν ὁ λόγος","es":"en el principio era el Verbo","prompt_es":"Di en el principio era el Verbo."},{"gr":"ὁ λόγος σὰρξ ἐγένετο","es":"el Verbo se hizo carne","prompt_es":"Di el Verbo se hizo carne."},{"gr":"οὕτως ἠγάπησεν ὁ θεὸς τὸν κόσμον","es":"de tal manera amó Dios al mundo","prompt_es":"Di de tal manera amó Dios al mundo."},{"gr":"μείζων δὲ τούτων ἡ ἀγάπη","es":"el mayor de ellos es el amor","prompt_es":"Di el mayor de ellos es el amor."},{"gr":"τετέλεσται","es":"consumado es, está terminado","prompt_es":"Di consumado es. Has terminado el curso."},{"gr":"εὐχαριστοῦμεν τῷ θεῷ","es":"damos gracias a Dios","prompt_es":"Di damos gracias a Dios."},{"gr":"ἀμήν","es":"amén","prompt_es":"Di amén."}],
"recon":[{"prompt_es":"Recita Juan uno uno.","answer_gr":"Ἐν ἀρχῇ ἦν ὁ λόγος, καὶ ὁ λόγος ἦν πρὸς τὸν θεόν, καὶ θεὸς ἦν ὁ λόγος.","answer_voice":M},{"prompt_es":"Recita Juan tres dieciséis.","answer_gr":"Οὕτως γὰρ ἠγάπησεν ὁ θεὸς τὸν κόσμον, ὥστε τὸν υἱὸν τὸν μονογενῆ ἔδωκεν, ἵνα πᾶς ὁ πιστεύων εἰς αὐτὸν ἔχῃ ζωὴν αἰώνιον.","answer_voice":M},{"prompt_es":"Di el mayor de ellos es el amor.","answer_gr":"Μείζων δὲ τούτων ἡ ἀγάπη.","answer_voice":M},{"prompt_es":"Di consumado es.","answer_gr":"Τετέλεσται.","answer_voice":M},{"prompt_es":"Di amén.","answer_gr":"Ἀμήν.","answer_voice":M}],
"verse":{"gr":"Ἡ χάρις τοῦ κυρίου Ἰησοῦ Χριστοῦ καὶ ἡ ἀγάπη τοῦ θεοῦ καὶ ἡ κοινωνία τοῦ ἁγίου πνεύματος μετὰ πάντων ὑμῶν. Ἀμήν.","voice":M,"ref_es":"Segunda de Corintios trece catorce, la bendición final:","explain_es":"La gracia del Señor Jesucristo, el amor de Dios, y la comunión del Espíritu Santo sean con todos ustedes. Amén. Reconoces cada palabra. χάρις, gracia. ἀγάπη, amor. κοινωνία, comunión. πνεύματος, Espíritu. Amén."},
"closing_es":"Τετέλεσται. Está terminado. Has completado noventa lecciones de griego koiné. Conoces más de seiscientas palabras que cubren más del noventa por ciento del texto del Nuevo Testamento. Puedes leer el prólogo de Juan, Romanos ocho, primera de Corintios trece, el Salmo veintitrés, y muchos otros textos. Has aprendido el idioma en el que fue escrito el Nuevo Testamento. Ἡ χάρις τοῦ κυρίου μετὰ σοῦ. Εἰρήνη σοι. Ἀμήν."}
