"""Lesson data 71-75: James practical, 1 Peter suffering, 1 John love"""
M = "el-GR-Chirp3-HD-Charon"
F = "el-GR-Chirp3-HD-Kore"

L71={"num":71,"intro_es":"Μάθημα ἑβδομήκοντα ἕν. Lección setenta y uno. Hoy leerás Santiago: fe y obras. Escucha.",
"dialogue":[(M,"Τί τὸ ὄφελος, ἀδελφοί μου, ἐὰν πίστιν λέγῃ τις ἔχειν, ἔργα δὲ μὴ ἔχῃ;"),(M,"Ἡ πίστις χωρὶς ἔργων νεκρά ἐστιν.")],
"context_es":"¿De qué sirve, hermanos míos, si alguien dice tener fe pero no tiene obras? La fe sin obras está muerta.",
"vocab":[{"gr":"ὄφελος","es":"provecho, utilidad","note_es":"ὄφελος significa provecho o utilidad. τί τὸ ὄφελος, de qué sirve. Escucha."},{"gr":"χωρίς","es":"sin, aparte de","note_es":"χωρίς significa sin o aparte de. Con genitivo. χωρὶς ἔργων, sin obras. Escucha."},{"gr":"νεκρά","es":"muerta (femenino)","note_es":"νεκρά es la forma femenina de νεκρός. ἡ πίστις νεκρά, la fe muerta. Escucha."},{"gr":"δείκνυμι","es":"mostrar","note_es":"δείκνυμι significa mostrar. δεῖξόν μοι, muéstrame. Escucha."},{"gr":"πειρασμός","es":"prueba, tentación","note_es":"πειρασμός significa prueba o tentación. Escucha."},{"gr":"ὑπομονή","es":"perseverancia","note_es":"Ya conoces ὑπομονή. Santiago dice que la prueba produce perseverancia. Escucha."}],
"phrases":[{"gr":"ἡ πίστις χωρὶς ἔργων νεκρά ἐστιν","es":"la fe sin obras está muerta","prompt_es":"Di la fe sin obras está muerta."},{"gr":"δεῖξόν μοι τὴν πίστιν σου","es":"muéstrame tu fe","prompt_es":"Di muéstrame tu fe."},{"gr":"ἐκ τῶν ἔργων μου","es":"por mis obras","prompt_es":"Di por mis obras."},{"gr":"ἡ δοκιμὴ τῆς πίστεως ὑπομονὴν κατεργάζεται","es":"la prueba de la fe produce perseverancia","prompt_es":"Di la prueba de la fe produce perseverancia."},{"gr":"γίνεσθε ποιηταὶ λόγου","es":"sean hacedores de la palabra","prompt_es":"Di sean hacedores de la palabra. ποιηταί es hacedores."},{"gr":"μὴ μόνον ἀκροαταί","es":"no solo oidores","prompt_es":"Di no solo oidores."}],
"recon":[{"prompt_es":"Di la fe sin obras está muerta.","answer_gr":"Ἡ πίστις χωρὶς ἔργων νεκρά ἐστιν.","answer_voice":M},{"prompt_es":"Di sean hacedores de la palabra, no solo oidores.","answer_gr":"Γίνεσθε ποιηταὶ λόγου καὶ μὴ μόνον ἀκροαταί.","answer_voice":M},{"prompt_es":"Di muéstrame tu fe.","answer_gr":"Δεῖξόν μοι τὴν πίστιν σου.","answer_voice":M}],
"verse":{"gr":"Γίνεσθε δὲ ποιηταὶ λόγου καὶ μὴ μόνον ἀκροαταί.","voice":M,"ref_es":"Santiago uno veintidós:","explain_es":"Sean hacedores de la palabra y no solo oidores. γίνεσθε, sean. ποιηταί, hacedores. λόγου, de la palabra. ἀκροαταί, oidores."},
"closing_es":"Aprendiste Santiago: ὄφελος provecho, χωρίς sin, δείκνυμι mostrar, πειρασμός prueba. Εἰρήνη σοι."}

L72={"num":72,"intro_es":"Μάθημα ἑβδομήκοντα δύο. Lección setenta y dos. Hoy leerás primera de Pedro: sufrimiento y esperanza. Escucha.",
"dialogue":[(M,"Εὐλογητὸς ὁ θεὸς καὶ πατὴρ τοῦ κυρίου ἡμῶν Ἰησοῦ Χριστοῦ, ὁ κατὰ τὸ πολὺ αὐτοῦ ἔλεος ἀναγεννήσας ἡμᾶς εἰς ἐλπίδα ζῶσαν.")],
"context_es":"Bendito el Dios y Padre de nuestro Señor Jesucristo, que según su gran misericordia nos hizo renacer para una esperanza viva.",
"vocab":[{"gr":"εὐλογητός","es":"bendito","note_es":"εὐλογητός significa bendito. Viene de εὐλογέω, bendecir. Escucha."},{"gr":"ἔλεος","es":"misericordia","note_es":"ἔλεος significa misericordia. Aparece veintisiete veces. Escucha."},{"gr":"ἀναγεννάω","es":"hacer renacer","note_es":"ἀναγεννάω significa hacer renacer. Viene de ἀνά, de nuevo, y γεννάω, engendrar. Escucha."},{"gr":"ζῶσα","es":"viva (femenino)","note_es":"ζῶσα es la forma femenina del participio de ζάω, vivir. ἐλπίδα ζῶσαν, esperanza viva. Escucha."},{"gr":"κληρονομία","es":"herencia","note_es":"κληρονομία significa herencia. Viene de κληρονομέω, heredar. Escucha."},{"gr":"ἄφθαρτος","es":"incorruptible","note_es":"ἄφθαρτος significa incorruptible. Viene de ἀ, sin, y φθείρω, corromper. Escucha."}],
"phrases":[{"gr":"εὐλογητὸς ὁ θεός","es":"bendito sea Dios","prompt_es":"Di bendito sea Dios."},{"gr":"κατὰ τὸ πολὺ αὐτοῦ ἔλεος","es":"según su gran misericordia","prompt_es":"Di según su gran misericordia."},{"gr":"εἰς ἐλπίδα ζῶσαν","es":"para una esperanza viva","prompt_es":"Di para una esperanza viva."},{"gr":"κληρονομίαν ἄφθαρτον","es":"herencia incorruptible","prompt_es":"Di herencia incorruptible."},{"gr":"ἀναγεννήσας ἡμᾶς","es":"habiéndonos hecho renacer","prompt_es":"Di habiéndonos hecho renacer."},{"gr":"δι᾽ ἀναστάσεως Ἰησοῦ Χριστοῦ","es":"por la resurrección de Jesucristo","prompt_es":"Di por la resurrección de Jesucristo."}],
"recon":[{"prompt_es":"Di bendito sea Dios.","answer_gr":"Εὐλογητὸς ὁ θεός.","answer_voice":M},{"prompt_es":"Di según su gran misericordia nos hizo renacer.","answer_gr":"Κατὰ τὸ πολὺ αὐτοῦ ἔλεος ἀναγεννήσας ἡμᾶς.","answer_voice":M},{"prompt_es":"Di para una esperanza viva.","answer_gr":"Εἰς ἐλπίδα ζῶσαν.","answer_voice":M}],
"verse":{"gr":"Εὐλογητὸς ὁ θεὸς καὶ πατὴρ τοῦ κυρίου ἡμῶν Ἰησοῦ Χριστοῦ.","voice":M,"ref_es":"Primera de Pedro uno tres:","explain_es":"Bendito el Dios y Padre de nuestro Señor Jesucristo. εὐλογητός, bendito. Reconoces θεός, πατήρ, κυρίου, Ἰησοῦ Χριστοῦ."},
"closing_es":"Aprendiste primera de Pedro: εὐλογητός bendito, ἔλεος misericordia, ἀναγεννάω renacer, ἄφθαρτος incorruptible. Εἰρήνη σοι."}

L73={"num":73,"intro_es":"Μάθημα ἑβδομήκοντα τρία. Lección setenta y tres. Hoy leerás primera de Juan: Dios es amor. Escucha.",
"dialogue":[(M,"Ὁ θεὸς ἀγάπη ἐστίν."),(M,"Ἐν τούτῳ ἐστὶν ἡ ἀγάπη, οὐχ ὅτι ἡμεῖς ἠγαπήκαμεν τὸν θεόν, ἀλλ᾽ ὅτι αὐτὸς ἠγάπησεν ἡμᾶς.")],
"context_es":"Dios es amor. En esto consiste el amor: no en que nosotros hayamos amado a Dios, sino en que él nos amó.",
"vocab":[{"gr":"ἀγάπη ἐστίν","es":"es amor","note_es":"ὁ θεὸς ἀγάπη ἐστίν. Dios es amor. Una de las declaraciones más profundas del Nuevo Testamento. Escucha."},{"gr":"ἠγαπήκαμεν","es":"hemos amado (perfecto)","note_es":"ἠγαπήκαμεν es el perfecto de ἀγαπάω. Hemos amado. Escucha."},{"gr":"ἠγάπησεν","es":"amó (aoristo)","note_es":"ἠγάπησεν es el aoristo de ἀγαπάω. Amó. Escucha."},{"gr":"ἱλασμός","es":"propiciación, expiación","note_es":"ἱλασμός significa propiciación o expiación. Él es la propiciación por nuestros pecados. Escucha."},{"gr":"φόβος","es":"miedo, temor","note_es":"φόβος significa miedo o temor. ἡ τελεία ἀγάπη ἔξω βάλλει τὸν φόβον, el amor perfecto echa fuera el temor. Escucha."},{"gr":"τέλειος","es":"perfecto, completo","note_es":"τέλειος significa perfecto o completo. Viene de τέλος, fin. Lo que ha llegado a su fin, completo. Escucha."}],
"phrases":[{"gr":"ὁ θεὸς ἀγάπη ἐστίν","es":"Dios es amor","prompt_es":"Di Dios es amor."},{"gr":"αὐτὸς ἠγάπησεν ἡμᾶς","es":"él nos amó","prompt_es":"Di él nos amó."},{"gr":"ἡ τελεία ἀγάπη ἔξω βάλλει τὸν φόβον","es":"el amor perfecto echa fuera el temor","prompt_es":"Di el amor perfecto echa fuera el temor."},{"gr":"αὐτός ἐστιν ἱλασμὸς περὶ τῶν ἁμαρτιῶν ἡμῶν","es":"él es la propiciación por nuestros pecados","prompt_es":"Di él es la propiciación por nuestros pecados."},{"gr":"ἀγαπῶμεν ἀλλήλους","es":"amémonos unos a otros","prompt_es":"Di amémonos unos a otros."},{"gr":"ὁ μὴ ἀγαπῶν οὐκ ἔγνω τὸν θεόν","es":"el que no ama no ha conocido a Dios","prompt_es":"Di el que no ama no ha conocido a Dios."}],
"recon":[{"prompt_es":"Di Dios es amor.","answer_gr":"Ὁ θεὸς ἀγάπη ἐστίν.","answer_voice":M},{"prompt_es":"Di el amor perfecto echa fuera el temor.","answer_gr":"Ἡ τελεία ἀγάπη ἔξω βάλλει τὸν φόβον.","answer_voice":M},{"prompt_es":"Di amémonos unos a otros.","answer_gr":"Ἀγαπῶμεν ἀλλήλους.","answer_voice":M}],
"verse":{"gr":"Ὁ θεὸς ἀγάπη ἐστίν, καὶ ὁ μένων ἐν τῇ ἀγάπῃ ἐν τῷ θεῷ μένει καὶ ὁ θεὸς ἐν αὐτῷ μένει.","voice":M,"ref_es":"Primera de Juan cuatro dieciséis:","explain_es":"Dios es amor, y el que permanece en el amor permanece en Dios y Dios en él. μένων, el que permanece. ἀγάπῃ, en el amor."},
"closing_es":"Aprendiste primera de Juan: ἱλασμός propiciación, φόβος temor, τέλειος perfecto. Y la declaración central: Dios es amor. Εἰρήνη σοι."}

L74={"num":74,"intro_es":"Μάθημα ἑβδομήκοντα τέσσαρα. Lección setenta y cuatro. Hoy leerás Gálatas: libertad en Cristo. Escucha.",
"dialogue":[(M,"Τῇ ἐλευθερίᾳ ἡμᾶς Χριστὸς ἠλευθέρωσεν· στήκετε οὖν καὶ μὴ πάλιν ζυγῷ δουλείας ἐνέχεσθε.")],
"context_es":"Para libertad Cristo nos libertó. Estén firmes pues, y no se sometan otra vez al yugo de esclavitud.",
"vocab":[{"gr":"ἐλευθερία","es":"libertad","note_es":"ἐλευθερία significa libertad. Aparece once veces. Escucha."},{"gr":"ἐλευθερόω","es":"liberar","note_es":"ἐλευθερόω significa liberar. ἠλευθέρωσεν es liberó. Escucha."},{"gr":"ζυγός","es":"yugo","note_es":"ζυγός significa yugo. ζυγῷ δουλείας, yugo de esclavitud. Escucha."},{"gr":"δουλεία","es":"esclavitud","note_es":"δουλεία significa esclavitud. Viene de δοῦλος, esclavo. Escucha."},{"gr":"στήκω","es":"estar firme","note_es":"στήκω significa estar firme. στήκετε es estén firmes. Escucha."},{"gr":"καρπὸς τοῦ πνεύματος","es":"fruto del Espíritu","note_es":"El fruto del Espíritu: amor, gozo, paz, paciencia, benignidad, bondad, fe, mansedumbre, dominio propio. Escucha."}],
"phrases":[{"gr":"τῇ ἐλευθερίᾳ ἡμᾶς Χριστὸς ἠλευθέρωσεν","es":"para libertad Cristo nos libertó","prompt_es":"Di para libertad Cristo nos libertó."},{"gr":"στήκετε οὖν","es":"estén firmes pues","prompt_es":"Di estén firmes pues."},{"gr":"μὴ πάλιν ζυγῷ δουλείας ἐνέχεσθε","es":"no se sometan al yugo de esclavitud","prompt_es":"Di no se sometan al yugo de esclavitud."},{"gr":"ὁ καρπὸς τοῦ πνεύματος","es":"el fruto del Espíritu","prompt_es":"Di el fruto del Espíritu."},{"gr":"ἀγάπη, χαρά, εἰρήνη","es":"amor, gozo, paz","prompt_es":"Di amor, gozo, paz. Los primeros tres frutos del Espíritu."},{"gr":"μακροθυμία, χρηστότης, ἀγαθωσύνη","es":"paciencia, benignidad, bondad","prompt_es":"Di paciencia, benignidad, bondad."}],
"recon":[{"prompt_es":"Di para libertad Cristo nos libertó.","answer_gr":"Τῇ ἐλευθερίᾳ ἡμᾶς Χριστὸς ἠλευθέρωσεν.","answer_voice":M},{"prompt_es":"Di estén firmes.","answer_gr":"Στήκετε.","answer_voice":M},{"prompt_es":"Di el fruto del Espíritu es amor, gozo, paz.","answer_gr":"Ὁ καρπὸς τοῦ πνεύματος ἐστιν ἀγάπη, χαρά, εἰρήνη.","answer_voice":M}],
"verse":{"gr":"Τῇ ἐλευθερίᾳ ἡμᾶς Χριστὸς ἠλευθέρωσεν.","voice":M,"ref_es":"Gálatas cinco uno:","explain_es":"Para libertad Cristo nos libertó. ἐλευθερίᾳ, para libertad. ἠλευθέρωσεν, libertó."},
"closing_es":"Aprendiste Gálatas: ἐλευθερία libertad, ζυγός yugo, δουλεία esclavitud, στήκω estar firme. Y el fruto del Espíritu. Εἰρήνη σοι."}

L75={"num":75,"intro_es":"Μάθημα ἑβδομήκοντα πέντε. Lección setenta y cinco. Repaso de tres cuartos del curso. Hoy leerás la gran comisión. Escucha.",
"dialogue":[(M,"Ἐδόθη μοι πᾶσα ἐξουσία ἐν οὐρανῷ καὶ ἐπὶ γῆς."),(M,"Πορευθέντες οὖν μαθητεύσατε πάντα τὰ ἔθνη, βαπτίζοντες αὐτοὺς εἰς τὸ ὄνομα τοῦ πατρὸς καὶ τοῦ υἱοῦ καὶ τοῦ ἁγίου πνεύματος.")],
"context_es":"Se me ha dado toda autoridad en el cielo y en la tierra. Vayan pues y hagan discípulos a todas las naciones, bautizándolos en el nombre del Padre, del Hijo y del Espíritu Santo.",
"vocab":[{"gr":"ἐξουσία","es":"autoridad, poder","note_es":"ἐξουσία significa autoridad o poder. Diferente de δύναμις que es poder como capacidad. ἐξουσία es poder como derecho. Aparece ciento dos veces. Escucha."},{"gr":"ἔθνος","es":"nación, gentil","note_es":"ἔθνος significa nación. En plural, τὰ ἔθνη, las naciones o los gentiles. Aparece ciento sesenta y dos veces. Escucha."},{"gr":"μαθητεύω","es":"hacer discípulos","note_es":"μαθητεύω significa hacer discípulos. Viene de μαθητής, discípulo. μαθητεύσατε es hagan discípulos. Escucha."},{"gr":"ἐδόθη","es":"fue dado (aoristo pasivo)","note_es":"ἐδόθη es el aoristo pasivo de δίδωμι. Fue dado. Se me ha dado. Escucha."},{"gr":"διδάσκοντες","es":"enseñando (participio)","note_es":"διδάσκοντες es enseñando, participio de διδάσκω. Escucha."},{"gr":"συντέλεια","es":"consumación, fin","note_es":"συντέλεια significa consumación o fin. Viene de σύν, juntos, y τέλος, fin. ἕως τῆς συντελείας τοῦ αἰῶνος, hasta el fin del siglo. Escucha."}],
"phrases":[{"gr":"πᾶσα ἐξουσία ἐν οὐρανῷ καὶ ἐπὶ γῆς","es":"toda autoridad en el cielo y en la tierra","prompt_es":"Di toda autoridad en el cielo y en la tierra."},{"gr":"πορευθέντες μαθητεύσατε πάντα τὰ ἔθνη","es":"vayan y hagan discípulos a todas las naciones","prompt_es":"Di vayan y hagan discípulos a todas las naciones."},{"gr":"βαπτίζοντες αὐτούς","es":"bautizándolos","prompt_es":"Di bautizándolos."},{"gr":"εἰς τὸ ὄνομα τοῦ πατρὸς καὶ τοῦ υἱοῦ καὶ τοῦ ἁγίου πνεύματος","es":"en el nombre del Padre, del Hijo y del Espíritu Santo","prompt_es":"Di en el nombre del Padre, del Hijo y del Espíritu Santo."},{"gr":"ἕως τῆς συντελείας τοῦ αἰῶνος","es":"hasta el fin del siglo","prompt_es":"Di hasta el fin del siglo."},{"gr":"ἰδοὺ ἐγὼ μεθ᾽ ὑμῶν εἰμι","es":"he aquí yo estoy con ustedes","prompt_es":"Di he aquí yo estoy con ustedes."}],
"recon":[{"prompt_es":"Di toda autoridad me ha sido dada en el cielo y en la tierra.","answer_gr":"Ἐδόθη μοι πᾶσα ἐξουσία ἐν οὐρανῷ καὶ ἐπὶ γῆς.","answer_voice":M},{"prompt_es":"Di vayan y hagan discípulos a todas las naciones.","answer_gr":"Πορευθέντες μαθητεύσατε πάντα τὰ ἔθνη.","answer_voice":M},{"prompt_es":"Di he aquí yo estoy con ustedes hasta el fin del siglo.","answer_gr":"Ἰδοὺ ἐγὼ μεθ᾽ ὑμῶν εἰμι πάσας τὰς ἡμέρας ἕως τῆς συντελείας τοῦ αἰῶνος.","answer_voice":M}],
"verse":{"gr":"Ἰδοὺ ἐγὼ μεθ᾽ ὑμῶν εἰμι πάσας τὰς ἡμέρας ἕως τῆς συντελείας τοῦ αἰῶνος.","voice":M,"ref_es":"Mateo veintiocho veinte:","explain_es":"He aquí yo estoy con ustedes todos los días hasta el fin del siglo. ἰδού, he aquí. μεθ᾽ ὑμῶν, con ustedes. πάσας τὰς ἡμέρας, todos los días. συντελείας, fin. αἰῶνος, del siglo."},
"closing_es":"Has completado setenta y cinco lecciones, tres cuartos del curso. Aprendiste la gran comisión: ἐξουσία autoridad, ἔθνος nación, μαθητεύω hacer discípulos. Εἰρήνη σοι."}
