"""Lesson data 61-65: Level 3 — Passion narrative, Epistolary, Argumentation"""
M = "el-GR-Chirp3-HD-Charon"
F = "el-GR-Chirp3-HD-Kore"

L61={"num":61,"intro_es":"Μάθημα ἑξήκοντα ἕν. Lección sesenta y uno. Bienvenido al tercer nivel: Ὁ Κήρυξ, el predicador. Hoy narrarás el arresto de Jesús en Getsemaní. Escucha.",
"dialogue":[(M,"Ὃν ἂν φιλήσω, αὐτός ἐστιν· κρατήσατε αὐτόν."),(M,"Χαῖρε, ῥαββί. Καὶ κατεφίλησεν αὐτόν."),(F,"Ἑταῖρε, ἐφ᾽ ὃ πάρει;")],
"context_es":"Judas dijo: al que yo bese, ese es, arréstenlo. Hola, maestro. Y lo besó. Jesús dijo: amigo, ¿a qué has venido?",
"vocab":[{"gr":"φιλέω","es":"besar, amar","note_es":"φιλέω significa besar o amar con afecto. Diferente de ἀγαπάω. Aparece veinticinco veces. Escucha."},{"gr":"κρατέω","es":"agarrar, arrestar","note_es":"κρατέω significa agarrar o arrestar. κρατήσατε es arréstenlo, imperativo aoristo. Aparece cuarenta y siete veces. Escucha."},{"gr":"ῥαββί","es":"maestro, rabí","note_es":"ῥαββί significa maestro o rabí. Es un título hebreo. Escucha."},{"gr":"μάχαιρα","es":"espada","note_es":"μάχαιρα significa espada. Pedro sacó su espada. Aparece veintinueve veces. Escucha."},{"gr":"παραδίδωμι","es":"entregar, traicionar","note_es":"παραδίδωμι significa entregar o traicionar. Viene de παρά, al lado, y δίδωμι, dar. Dar al lado, entregar a otro. Aparece ciento diecinueve veces. Escucha."},{"gr":"ἑταῖρος","es":"amigo, compañero","note_es":"ἑταῖρος significa amigo o compañero. Jesús llamó así a Judas. Escucha."}],
"phrases":[{"gr":"κρατήσατε αὐτόν","es":"arréstenlo","prompt_es":"Di arréstenlo."},{"gr":"κατεφίλησεν αὐτόν","es":"lo besó","prompt_es":"Di lo besó. κατεφίλησεν es besó intensamente, de καταφιλέω."},{"gr":"ὁ παραδιδοὺς αὐτόν","es":"el que lo entregaba","prompt_es":"Di el que lo entregaba. Participio de παραδίδωμι."},{"gr":"ἀπόστρεψον τὴν μάχαιράν σου","es":"guarda tu espada","prompt_es":"Di guarda tu espada. Jesús dijo esto a Pedro."},{"gr":"πάντες γὰρ οἱ λαβόντες μάχαιραν ἐν μαχαίρῃ ἀπολοῦνται","es":"todos los que toman espada, a espada perecerán","prompt_es":"Di todos los que toman espada, a espada perecerán."},{"gr":"ἐφ᾽ ὃ πάρει","es":"¿a qué has venido?","prompt_es":"Di a qué has venido. Jesús le dijo esto a Judas."}],
"recon":[{"other_gr":"Χαῖρε, ῥαββί.","other_voice":M,"prompt_es":"Judas te saluda. Responde como Jesús: amigo, a qué has venido.","answer_gr":"Ἑταῖρε, ἐφ᾽ ὃ πάρει;","answer_voice":F},{"prompt_es":"Di guarda tu espada.","answer_gr":"Ἀπόστρεψον τὴν μάχαιράν σου.","answer_voice":F},{"prompt_es":"Di el que lo entregaba.","answer_gr":"Ὁ παραδιδοὺς αὐτόν.","answer_voice":F}],
"verse":{"gr":"Ἑταῖρε, ἐφ᾽ ὃ πάρει;","voice":M,"ref_es":"Mateo veintiséis cincuenta:","explain_es":"Amigo, ¿a qué has venido? Las palabras de Jesús a Judas en el momento de la traición."},
"closing_es":"Aprendiste la narrativa del arresto: φιλέω besar, κρατέω arrestar, παραδίδωμι entregar, μάχαιρα espada. Εἰρήνη σοι."}

L62={"num":62,"intro_es":"Μάθημα ἑξήκοντα δύο. Lección sesenta y dos. Hoy narrarás el juicio ante Pilato. Escucha.",
"dialogue":[(M,"Σὺ εἶ ὁ βασιλεὺς τῶν Ἰουδαίων;"),(F,"Σὺ λέγεις."),(M,"Τί οὖν ποιήσω Ἰησοῦν τὸν λεγόμενον Χριστόν;"),(F,"Σταυρωθήτω!")],
"context_es":"¿Eres tú el rey de los judíos? Tú lo dices. ¿Qué haré entonces con Jesús llamado Cristo? ¡Sea crucificado!",
"vocab":[{"gr":"βασιλεύς","es":"rey","note_es":"βασιλεύς significa rey. Aparece ciento quince veces. ὁ βασιλεὺς τῶν Ἰουδαίων, el rey de los judíos. Escucha."},{"gr":"Ἰουδαῖος","es":"judío","note_es":"Ἰουδαῖος significa judío. Aparece ciento noventa y cinco veces. Escucha."},{"gr":"σταυρόω","es":"crucificar","note_es":"Ya conoces σταυρόω. σταυρωθήτω es sea crucificado, imperativo pasivo. Escucha."},{"gr":"ἀθῷος","es":"inocente","note_es":"ἀθῷος significa inocente. Viene de ἀ, sin, y θωή, castigo. Sin castigo, inocente. Pilato dijo: soy inocente de esta sangre. Escucha."},{"gr":"λαός","es":"pueblo","note_es":"λαός significa pueblo. Aparece ciento cuarenta y dos veces. Escucha."},{"gr":"ἡγεμών","es":"gobernador","note_es":"ἡγεμών significa gobernador. Pilato era ἡγεμών de Judea. Escucha."}],
"phrases":[{"gr":"σὺ εἶ ὁ βασιλεὺς τῶν Ἰουδαίων;","es":"¿eres tú el rey de los judíos?","prompt_es":"Pregunta como Pilato: eres tú el rey de los judíos."},{"gr":"σὺ λέγεις","es":"tú lo dices","prompt_es":"Di tú lo dices. La respuesta de Jesús."},{"gr":"σταυρωθήτω","es":"¡sea crucificado!","prompt_es":"Di sea crucificado. El grito de la multitud."},{"gr":"ἀθῷός εἰμι ἀπὸ τοῦ αἵματος τούτου","es":"soy inocente de esta sangre","prompt_es":"Di soy inocente de esta sangre. Las palabras de Pilato."},{"gr":"τί κακὸν ἐποίησεν;","es":"¿qué mal hizo?","prompt_es":"Pregunta qué mal hizo."},{"gr":"πᾶς ὁ λαός","es":"todo el pueblo","prompt_es":"Di todo el pueblo."}],
"recon":[{"other_gr":"Σὺ εἶ ὁ βασιλεὺς τῶν Ἰουδαίων;","other_voice":M,"prompt_es":"Pilato te pregunta. Responde como Jesús.","answer_gr":"Σὺ λέγεις.","answer_voice":F},{"prompt_es":"Pregunta qué mal hizo.","answer_gr":"Τί κακὸν ἐποίησεν;","answer_voice":F},{"prompt_es":"Di soy inocente de esta sangre.","answer_gr":"Ἀθῷός εἰμι ἀπὸ τοῦ αἵματος τούτου.","answer_voice":F}],
"verse":{"gr":"Τί οὖν ποιήσω Ἰησοῦν τὸν λεγόμενον Χριστόν;","voice":M,"ref_es":"Mateo veintisiete veintidós:","explain_es":"¿Qué haré entonces con Jesús llamado Cristo? τί, qué. οὖν, entonces. ποιήσω, haré. λεγόμενον, llamado, participio pasivo."},
"closing_es":"Aprendiste el juicio: βασιλεύς rey, Ἰουδαῖος judío, ἀθῷος inocente, λαός pueblo, ἡγεμών gobernador. Εἰρήνη σοι."}

L63={"num":63,"intro_es":"Μάθημα ἑξήκοντα τρία. Lección sesenta y tres. Hoy narrarás la crucifixión y resurrección. Escucha.",
"dialogue":[(M,"Ἠγέρθη, οὐκ ἔστιν ὧδε· ἴδε ὁ τόπος ὅπου ἔθηκαν αὐτόν."),(F,"Ὑπάγετε εἴπατε τοῖς μαθηταῖς αὐτοῦ ὅτι ἠγέρθη ἀπὸ τῶν νεκρῶν.")],
"context_es":"Ha resucitado, no está aquí. Miren el lugar donde lo pusieron. Vayan, digan a sus discípulos que ha resucitado de los muertos.",
"vocab":[{"gr":"ἠγέρθη","es":"fue levantado, resucitó","note_es":"Ya conoces ἠγέρθη. Aoristo pasivo de ἐγείρω. Ha resucitado. Escucha."},{"gr":"ὑπάγω","es":"ir, irse","note_es":"ὑπάγω significa ir o irse. ὑπάγετε es vayan. Aparece setenta y nueve veces. Escucha."},{"gr":"ἐφοβοῦντο","es":"tenían miedo (imperfecto)","note_es":"ἐφοβοῦντο significa tenían miedo. Imperfecto de φοβέομαι. Las mujeres tenían miedo en la tumba. Escucha."},{"gr":"τρόμος","es":"temblor","note_es":"τρόμος significa temblor. Escucha."},{"gr":"ἔκστασις","es":"asombro, éxtasis","note_es":"ἔκστασις significa asombro o éxtasis. Viene de ἐκ, fuera, y ἵστημι, estar. Estar fuera de sí. Escucha."},{"gr":"ὀπίσω","es":"detrás, después","note_es":"Ya conoces ὀπίσω, detrás. Jesús resucitado dice: voy delante de ustedes a Galilea. Escucha."}],
"phrases":[{"gr":"ἠγέρθη, οὐκ ἔστιν ὧδε","es":"ha resucitado, no está aquí","prompt_es":"Di ha resucitado, no está aquí."},{"gr":"ἴδε ὁ τόπος","es":"mira el lugar","prompt_es":"Di mira el lugar."},{"gr":"ὑπάγετε εἴπατε τοῖς μαθηταῖς","es":"vayan, digan a los discípulos","prompt_es":"Di vayan, digan a los discípulos."},{"gr":"ἠγέρθη ἀπὸ τῶν νεκρῶν","es":"resucitó de los muertos","prompt_es":"Di resucitó de los muertos."},{"gr":"μὴ φοβεῖσθε","es":"no teman","prompt_es":"Di no teman. El ángel dijo esto a las mujeres."},{"gr":"μὴ ἐκθαμβεῖσθε","es":"no se asusten","prompt_es":"Di no se asusten."}],
"recon":[{"prompt_es":"Eres el ángel en la tumba. Di ha resucitado, no está aquí.","answer_gr":"Ἠγέρθη, οὐκ ἔστιν ὧδε.","answer_voice":M},{"prompt_es":"Di vayan, digan a los discípulos que resucitó.","answer_gr":"Ὑπάγετε εἴπατε τοῖς μαθηταῖς αὐτοῦ ὅτι ἠγέρθη.","answer_voice":M},{"prompt_es":"Di no teman.","answer_gr":"Μὴ φοβεῖσθε.","answer_voice":M}],
"verse":{"gr":"Ἠγέρθη, οὐκ ἔστιν ὧδε· ἴδε ὁ τόπος ὅπου ἔθηκαν αὐτόν.","voice":M,"ref_es":"Marcos dieciséis seis:","explain_es":"Ha resucitado, no está aquí. Miren el lugar donde lo pusieron. ἠγέρθη, resucitó. ὧδε, aquí. τόπος, lugar. ἔθηκαν, pusieron."},
"closing_es":"Narraste la crucifixión y resurrección. Aprendiste ὑπάγω ir, ἔκστασις asombro, τρόμος temblor. Εἰρήνη σοι."}

L64={"num":64,"intro_es":"Μάθημα ἑξήκοντα τέσσαρα. Lección sesenta y cuatro. Hoy aprenderás el estilo de las cartas de Pablo: argumentación con conectores. Escucha.",
"dialogue":[(M,"Δικαιωθέντες οὖν ἐκ πίστεως εἰρήνην ἔχομεν πρὸς τὸν θεὸν διὰ τοῦ κυρίου ἡμῶν Ἰησοῦ Χριστοῦ.")],
"context_es":"Justificados pues por la fe, tenemos paz para con Dios por medio de nuestro Señor Jesucristo. Romanos cinco uno.",
"vocab":[{"gr":"δικαιόω","es":"justificar","note_es":"Ya conoces δικαιόω. δικαιωθέντες es habiendo sido justificados, participio aoristo pasivo. Escucha."},{"gr":"διά","es":"por medio de, a través de","note_es":"Ya conoces διά. Con genitivo significa por medio de o a través de. διὰ τοῦ κυρίου, por medio del Señor. Escucha."},{"gr":"ὥσπερ","es":"así como","note_es":"ὥσπερ significa así como. Pablo lo usa para comparaciones. Escucha."},{"gr":"οὕτως","es":"así, de esta manera","note_es":"οὕτως significa así o de esta manera. ὥσπερ... οὕτως, así como... así también. Escucha."},{"gr":"λογίζομαι","es":"considerar, calcular","note_es":"λογίζομαι significa considerar o calcular. Es deponente. λογιζόμεθα, consideramos. Escucha."},{"gr":"ἄρα","es":"por lo tanto","note_es":"ἄρα significa por lo tanto. Introduce una conclusión. Escucha."}],
"phrases":[{"gr":"δικαιωθέντες ἐκ πίστεως","es":"justificados por la fe","prompt_es":"Di justificados por la fe."},{"gr":"εἰρήνην ἔχομεν πρὸς τὸν θεόν","es":"tenemos paz para con Dios","prompt_es":"Di tenemos paz para con Dios."},{"gr":"διὰ τοῦ κυρίου ἡμῶν","es":"por medio de nuestro Señor","prompt_es":"Di por medio de nuestro Señor."},{"gr":"ὥσπερ... οὕτως καί","es":"así como... así también","prompt_es":"Di así como, así también."},{"gr":"λογιζόμεθα γάρ","es":"porque consideramos","prompt_es":"Di porque consideramos."},{"gr":"ἄρα οὖν","es":"por lo tanto entonces","prompt_es":"Di por lo tanto entonces. Doble conector paulino."}],
"recon":[{"prompt_es":"Di justificados por la fe tenemos paz para con Dios.","answer_gr":"Δικαιωθέντες ἐκ πίστεως εἰρήνην ἔχομεν πρὸς τὸν θεόν.","answer_voice":M},{"prompt_es":"Di por medio de nuestro Señor Jesucristo.","answer_gr":"Διὰ τοῦ κυρίου ἡμῶν Ἰησοῦ Χριστοῦ.","answer_voice":M},{"prompt_es":"Di por lo tanto entonces.","answer_gr":"Ἄρα οὖν.","answer_voice":M}],
"verse":{"gr":"Λογιζόμεθα γὰρ δικαιοῦσθαι πίστει ἄνθρωπον χωρὶς ἔργων νόμου.","voice":M,"ref_es":"Romanos tres veintiocho:","explain_es":"Porque consideramos que el hombre es justificado por la fe sin las obras de la ley. λογιζόμεθα, consideramos. δικαιοῦσθαι, ser justificado. πίστει, por fe. χωρίς, sin. ἔργων, obras. νόμου, de la ley."},
"closing_es":"Aprendiste argumentación paulina: ὥσπερ así como, οὕτως así, λογίζομαι considerar, ἄρα por lo tanto. Εἰρήνη σοι."}

L65={"num":65,"intro_es":"Μάθημα ἑξήκοντα πέντε. Lección sesenta y cinco. Hoy aprenderás sobre la armadura de Dios. Efesios seis. Escucha.",
"dialogue":[(M,"Ἐνδύσασθε τὴν πανοπλίαν τοῦ θεοῦ."),(M,"Στῆτε οὖν περιζωσάμενοι τὴν ὀσφὺν ὑμῶν ἐν ἀληθείᾳ.")],
"context_es":"Vístanse con toda la armadura de Dios. Estén firmes, ceñidos con la verdad.",
"vocab":[{"gr":"ἐνδύω","es":"vestir, revestir","note_es":"ἐνδύω significa vestir o revestir. Viene de ἐν, dentro, y δύω, meter. ἐνδύσασθε es vístanse. Escucha."},{"gr":"πανοπλία","es":"armadura completa","note_es":"πανοπλία significa armadura completa. Viene de πᾶς, todo, y ὅπλον, arma. Escucha."},{"gr":"ἵστημι","es":"poner de pie, estar firme","note_es":"Ya conoces ἵστημι. στῆτε es estén firmes, imperativo aoristo. Escucha."},{"gr":"θώραξ","es":"coraza, peto","note_es":"θώραξ significa coraza o peto. θώρακα τῆς δικαιοσύνης, la coraza de la justicia. Escucha."},{"gr":"ἀσπίς","es":"escudo","note_es":"ἀσπίς significa escudo. τὸν θυρεὸν τῆς πίστεως, el escudo de la fe. Escucha."},{"gr":"περικεφαλαία","es":"casco","note_es":"περικεφαλαία significa casco. Viene de περί, alrededor, y κεφαλή, cabeza. Lo que rodea la cabeza. Escucha."}],
"phrases":[{"gr":"ἐνδύσασθε τὴν πανοπλίαν τοῦ θεοῦ","es":"vístanse con la armadura de Dios","prompt_es":"Di vístanse con la armadura de Dios."},{"gr":"στῆτε οὖν","es":"estén firmes entonces","prompt_es":"Di estén firmes entonces."},{"gr":"τὸν θώρακα τῆς δικαιοσύνης","es":"la coraza de la justicia","prompt_es":"Di la coraza de la justicia."},{"gr":"τὸν θυρεὸν τῆς πίστεως","es":"el escudo de la fe","prompt_es":"Di el escudo de la fe."},{"gr":"τὴν περικεφαλαίαν τοῦ σωτηρίου","es":"el casco de la salvación","prompt_es":"Di el casco de la salvación. σωτήριον es salvación."},{"gr":"τὴν μάχαιραν τοῦ πνεύματος","es":"la espada del Espíritu","prompt_es":"Di la espada del Espíritu."}],
"recon":[{"prompt_es":"Di vístanse con la armadura de Dios.","answer_gr":"Ἐνδύσασθε τὴν πανοπλίαν τοῦ θεοῦ.","answer_voice":M},{"prompt_es":"Di el escudo de la fe.","answer_gr":"Τὸν θυρεὸν τῆς πίστεως.","answer_voice":M},{"prompt_es":"Di la espada del Espíritu.","answer_gr":"Τὴν μάχαιραν τοῦ πνεύματος.","answer_voice":M}],
"verse":{"gr":"Ἐνδύσασθε τὴν πανοπλίαν τοῦ θεοῦ πρὸς τὸ δύνασθαι ὑμᾶς στῆναι πρὸς τὰς μεθοδείας τοῦ διαβόλου.","voice":M,"ref_es":"Efesios seis once:","explain_es":"Vístanse con toda la armadura de Dios para que puedan resistir las asechanzas del diablo. πανοπλίαν, armadura. δύνασθαι, poder. στῆναι, estar firmes. μεθοδείας, asechanzas. διαβόλου, del diablo."},
"closing_es":"Aprendiste la armadura de Dios: ἐνδύω vestir, πανοπλία armadura, θώραξ coraza, ἀσπίς escudo, περικεφαλαία casco. Εἰρήνη σοι."}
